### ISSUE TITLE
Serious Sam Classic First Encounter (GOG) doesn't start

### ISSUE THREAD

**Issue by flytrapdev** [Heroic-Games-Launcher/HeroicGamesLauncher#1014]
### Describe the bug

Heroic cannot launch Serious Sam The First Encounter (GOG version).
After installing and launching the game, I get the following error :
![image](https://user-images.githubusercontent.com/68333938/155612230-6f9b60af-4774-4abf-9f77-52ab4fbfa31d.png)

The issue seems to come from the executable path.
The game's executable is located in the 'Bin' folder, but Heroic looks for 'bin' instead and doesn't find it.

After renaming the folder to 'bin' the game worked as expected.

### Add logs

Launch Command:           STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/matthieu/.steam/steam STEAM_COMPAT_DATA_PATH='/home/matthieu/Games/Heroic/Prefixes/Serious-Sam-The-First-Encounter'   /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl launch "/home/matthieu/Games/Heroic/Serious Sam The First Encounter"  1207658876 --no-wine --wrapper "'/home/matthieu/.steam/steam/steamapps/common/Proton 7.0/proton' run"  --os windows  
        System Info:
        
  Heroic Version: 2.2.1 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Ubuntu KERNEL: 5.13.0-30-generic ARCH: x64
  CPU: AMD Ryzen 5 2600X Six-Core Processor @3.6 GOVERNOR: ondemand
  RAM: Total: 16.7 GB Available: 14.5 GB
  GRAPHICS: GPU0: NVIDIA GeForce GTX 1070 Ti VRAM: 8192MB DRIVER: 510.47.03 
  PROTOCOL: x11
  
        Game Settings: {
	"checkUpdatesInterval": 10,
	"enableUpdates": false,
	"addDesktopShortcuts": false,
	"addStartMenuShortcuts": false,
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"checkForUpdatesOnStartup": true,
	"customWinePaths": [],
	"defaultInstallPath": "/home/matthieu/Games/Heroic",
	"defaultWinePrefix": "/home/matthieu/Games/Heroic/Prefixes",
	"language": "en",
	"maxWorkers": 0,
	"nvidiaPrime": false,
	"otherOptions": "",
	"showUnrealMarket": false,
	"showFps": false,
	"useGameMode": false,
	"userInfo": {
		"epicId": "",
		"name": "matthieu"
	},
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/matthieu/Games/Heroic/Prefixes/Serious-Sam-The-First-Encounter",
	"wineVersion": {
		"bin": "'/home/matthieu/.steam/steam/steamapps/common/Proton 7.0/proton'",
		"name": "Proton - Proton 7.0"
	},
	"altLegendaryBin": "",
	"audioFix": false,
	"darkTrayIcon": false,
	"discordRPC": false,
	"egsLinkedPath": "",
	"enableEsync": false,
	"enableFsync": false,
	"exitToTray": false,
	"maxRecentGames": 5,
	"offlineMode": false,
	"showMangohud": false,
	"startInTray": false,
	"maxSharpness": 2,
	"savesPath": "",
	"targetExe": "",
	"useSteamRuntime": false
}

        Game Log:
        Traceback (most recent call last):
  File "gogdl/cli.py", line 35, in <module>
  File "gogdl/cli.py", line 32, in main
  File "gogdl/launch.py", line 55, in launch
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1821, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/home/matthieu/Games/Heroic/Serious Sam The First Encounter/bin'
[26800] Failed to execute script 'cli' due to unhandled exception!

### Steps to reproduce

1. Download and install Serious Sam : The First Encounter from GOG
2. Click on "Play now"
3. See error

### Expected behavior

The game should start as normal.

### Screenshots

Serious Sam game data : 
![image](https://user-images.githubusercontent.com/68333938/155613875-4b037a52-9f1d-459a-99ab-d570360cf89e.png)

### System Information

- OS [e. g. "Ubuntu"]: Kubuntu 20.04
- Heroic Version [e. g. 2.1.1]: 2.2.1

**Comment by imLinguin** [comment]
Thanks for reporting this. It's good to know there are games out there that rely on Window's case insensitive file system.

**Comment by flavioislima** [comment]
> Thanks for reporting this. It's good to know there are games out there that rely on Window's case insensitive file system.

If this is related to case-insensitive so it will affect MacOS as well. Because Mac can have case-sensitive FS but it's not the default option when installing it. Most of them will have case-insensitive, that is the default.

**Comment by flavioislima** [comment]
@imLinguin do you think this was fixed with your latest changes?

**Comment by imLinguin** [comment]
I haven't touched that yet, I'll try to fix that and #1095.

**Comment by imLinguin** [comment]
Please test this gogdl build: https://github.com/Heroic-Games-Launcher/heroic-gogdl/actions/runs/1973754980

- Download and extract zip
- Make binary executable
- Set it as alternative GOGDL binary in Heroic
- Relaunch heroic

**Comment by flytrapdev** [comment]
I am getting a different error now.
There is no window that pops up, instead the game just stops and the "playing (stop)" button changes to "play now" without any error message.

The logs are as follows :
```
Launch Command: "/home/matthieu/Games/gogdl/gogdl" launch "/home/matthieu/Games/Heroic/Serious Sam The First Encounter" 1207658876 --wine '/home/matthieu/.steam/steam/steamapps/common/Proton 7.0/proton' --wine-prefix '/home/matthieu/Games/Heroic/Prefixes/Serious-Sam-The-First-Encounter' --os windows
        System Info:
        
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Ubuntu KERNEL: 5.13.0-35-generic ARCH: x64
  CPU: AMD Ryzen 5 2600X Six-Core Processor @3.6 GOVERNOR: ondemand
  RAM: Total: 16.7 GB Available: 13.7 GB
  GRAPHICS: GPU0: NVIDIA GeForce GTX 1070 Ti VRAM: 8192MB DRIVER: 510.47.03 
  PROTOCOL: x11
  
        Game Settings: {
	"altLegendaryBin": "",
	"altGogdlBin": "/home/matthieu/Games/gogdl/gogdl",
	"addDesktopShortcuts": false,
	"addStartMenuShortcuts": false,
	"audioFix": false,
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"checkForUpdatesOnStartup": true,
	"customWinePaths": [],
	"darkTrayIcon": false,
	"defaultInstallPath": "/home/matthieu/Games/Heroic",
	"defaultWinePrefix": "/home/matthieu/Games/Heroic/Prefixes",
	"discordRPC": false,
	"egsLinkedPath": "",
	"enableEsync": false,
	"enableFsync": false,
	"exitToTray": false,
	"language": "en",
	"maxRecentGames": 5,
	"maxWorkers": 0,
	"minimizeOnLaunch": false,
	"nvidiaPrime": false,
	"offlineMode": false,
	"otherOptions": "",
	"showFps": false,
	"showMangohud": false,
	"showUnrealMarket": false,
	"startInTray": false,
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/matthieu/Games/Heroic/Prefixes/Serious-Sam-The-First-Encounter",
	"wineVersion": {
		"bin": "'/home/matthieu/.steam/steam/steamapps/common/Proton 7.0/proton'",
		"name": "Proton - Proton 7.0"
	},
	"maxSharpness": 2,
	"savesPath": "",
	"targetExe": "",
	"useSteamRuntime": false
}

        Game Log:
        Proton: No compat data path?
```

There is indeed a prefix at /home/matthieu/Games/Heroic/Prefix/Serious-Sam-The-First-Encounter/ but it's empty.

**Comment by imLinguin** [comment]
Looks like this is a bug with proton in general
could you try with Wine-GE?

**Comment by flytrapdev** [comment]
I launched the game with Proton-7.1-GE-2 and it worked !

However I don't know what was happening earlier, because I tried it again with Proton 7.0 and it also worked. 
Maybe it was a configuration issue.

In any case the issue seems to have been resolved as the game now works as expected.

(As you said in your edit, it's possible that switching proton versions back and forth is what fixed it).

However, I've noticed something when looking at the game files :
![image](https://user-images.githubusercontent.com/68333938/158033611-0146da77-247e-4359-b964-869f5e66d30c.png)

Some folders have backslashes in their name, suggesting they were intended to be inside other folders.
It doesn't seem to prevent the game from running but I haven't tested it extensively.
This is unrelated, so maybe I should open another issue.

**Comment by imLinguin** [comment]
https://github.com/Heroic-Games-Launcher/heroic-gogdl/actions/runs/1974325334
This should fix it, you can either reinstall or repair the game

**Comment by flytrapdev** [comment]
That fixed it, the folders were extracted correctly.

Many thanks for resolving these issues !

**Comment by wiryfuture** [comment]
fixed?

**Comment by flytrapdev** [comment]
@wiryfuture the commit which fixes this is in the "testing" branch of the gogdl repo

As such, the issue isn't fixed yet, but I'm assuming it will be when the testing branch gets merged
