### ISSUE TITLE
[General] Add DLCs Manager (Install, uninstall, update)

### ISSUE THREAD

**Issue by Patrxgt** [Heroic-Games-Launcher/HeroicGamesLauncher#1119]
### Problem description

When you use games library for either GOG or Epic, you have DLCs for every each of your game listed as standalone games.

### Feature description

I think, that the best option would be listing DLCs in the game's menu (the one after clicking on the game's thumbnail) in the "DLC's" section, which could be placed between "Info" and "Tools" sections. 

### Alternatives

If solution listed above in impossible to do, then it would be nice to at least hide DLCs from the library and show them in the "Info" section in every each game menu above install button.

**Comment by snoozysoft** [comment]
If you can make this like how Steam handles it and allow the user to uncheck a DLC to prevent it from being installed or showing up in game (perhaps even going so far as to giving us such checkboxes before downloading of the game occurs, that'd be absolutely fantastic tbh.

**Comment by lumingzh** [comment]
Yes, the library is a mess now because of some games which have many DLCs.

**Comment by Nocccer** [comment]
I think this is implemented, if i'm correct? Can you close the ticket, if so?

**Comment by Patrxgt** [comment]
Not really, I still have DLCs showed as a separate games in the library, so there is some more work to do about that.

**Comment by imLinguin** [comment]
DLC's for GOG handling can still be improved. Currently you can only install DLCs when downloading the game. Not great solution if you buy DLC that just came out and you want to install it additionally.

**Comment by aifreedom** [comment]
+1 to what @imLinguin said. I installed Witcher 3 without checking the box to download all DLC. And now I can’t find a way to add them.

**Comment by arthurlutz** [comment]
In case it can help, https://github.com/sharkwouter/minigalaxy/ has a working implementation of DLC installing for GOG. Right now the UI has a submenu (right clic) where the list of DLC shows up and you can activate them which installs the DLC in the background.

**Comment by umasse** [comment]
I had problems with installing the DLC for the game Control. With latest Heroic as of today, installed as a flatpak, no DLC was visible.
I was able to install the DLCs using `legendary` from the command line, using this to run it from the Heroic flatpak itself:
```
flatpak run --command=legendary com.heroicgameslauncher.hgl <command>
```
I used the command `list` to find out the app names for the DLCs, and then the command `install`.
Because it is the same `legendary` as the one that Heroic uses, I guess, it picked up the config file perfectly, and for now this is my workaround. Adding it here in case it helps someone.

**Comment by arkni8** [comment]
@umasse Hey, any idea how to get this working on Windows?
I have installed `legendary` (for Windows) and actually installed the DLC I need, in the same folder as the parent game, but the game doesn't detect the DLC. Any idea what to do here?

**Comment by umasse** [comment]
@arkni8 Sorry, I don't have Windows. The only thing I can suggest is to make sure you use the same config file that Heroic has somewhere. Good luck!

**Comment by flavioislima** [comment]
Done!

**Comment by Citizen839X** [comment]
I still don't understand how exactly works the whole thing in Heroic when you have a GOG title (standalone .exe) and you installing it through the "add game" option because in my case (Dead Cells) I succeeded to install the main game but when I want logically add the DLC too through the wine .exe inside the prefix because, correct me if I am wrong here, that option is supposed to work for an already installed wine bottle associated to the title, so, the system must see the main game in order to work with the DLCs, but I get a runtime error about "could not call proc.".

Is it a Heroic bug, a limit, or it's just me?
