### ISSUE TITLE
[Linux][gog] alternative executable is not being started (starts as usual)

### ISSUE THREAD

**Issue by pppbb** [Heroic-Games-Launcher/HeroicGamesLauncher#1141]
### Describe the bug

I have a problem with a specific game that is Grim Fandango Remastered. Using Heroic to start the game doesnt work. But i discovered that running the game executable directly starts the game. So i chose alternative executable and tried to start the game(with heroic) but it failed to start. So i post this as a probable bug.

### Add logs

Launch Command:   "/opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl" launch "/home/piotr/GOG Games/Grim Fandango Remastererd"  1207667183 --platform=linux  
        System Info:
        
  Heroic Version: 2.2.6 Oden
  Legendary Version: invalid
  OS: Arch KERNEL: 5.17.0-rc8-247-tkg-cfs ARCH: x64
  CPU: AMD Ryzen 9 5900X 12-Core Processor @3.7 GOVERNOR: schedutil
  RAM: Total: 67.4 GB Available: 59.6 GB
  GRAPHICS: GPU0: Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] VRAM: 1MB DRIVER:  
  PROTOCOL: wayland
  
        Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"enableEsync": true,
	"maxSharpness": 2,
	"launcherArgs": "",
	"nvidiaPrime": false,
	"offlineMode": true,
	"otherOptions": "_MESA_LOADER_DRIVER_OVERRIDE=zink MANGOHUD=1 VKD3D_CONFIG=dxr RADV_PERFTEST=rt VK_ICD_FILENAMES='/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json'  DXVK_LOG_PATH=/home/piotr/dxvk/logs/ DXVK_STATE_CACHE_PATH=/home/piotr/dxvk/state.cache/  MANGOHUD_CONFIG=cpu_temp,gpu_temp,gpu_core_clock,gpu_mem_clock,ram,vram,vulkan_driver,gpu_name,gpu_power,cpu_mhz,wine,engine_version,fps_limit=120",
	"savesPath": "",
	"showFps": false,
	"showMangohud": false,
	"targetExe": "'/run/media/piotr/Linux/GOG Games/Grim Fandango Remastererd/game/bin/GrimFandango'",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/piotr/Games/Heroic/Prefixes/Grim-Fandango-Remastered",
	"wineVersion": {
		"bin": "/usr/bin/wine",
		"name": "Wine Default - wine-7.2 (Staging)"
	},
	"useSteamRuntime": false
}

        Game Log:
        
        

### Steps to reproduce

1. run heroic
2. select gog game
3. in options choose alternative executable
4. run game

### Expected behavior

Game starts with alternative executable.

### System Information

- OS [Arch Linux]: 
- Heroic Version [2.2.6]:

**Comment by dawidgarus** [comment]
Should be fixed by https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1133

**Comment by pppbb** [comment]
i tested latest appimage and it still doesnt work(loading alt executable) for grim fandango. i also tested heroes 3 with hd mod and it runs fine - heroic successfuly loads alt executable.

**Comment by imLinguin** [comment]
Looks like it's a bug in gogdl, I'll push the patch and send you a binary to test later.

**Comment by imLinguin** [comment]
Try this gogdl binary, make it executable and set it in Heroic settings
https://github.com/Heroic-Games-Launcher/heroic-gogdl/actions/runs/2022915444

**Comment by pppbb** [comment]
With the new gogdl binary game starts as expected.

**Comment by pppbb** [comment]
> With the new gogdl binary game starts as expected.

i mean it works now. sorry for my english.

**Comment by pppbb** [comment]
I want to report similliar problems with Unreal Gold.
Heroic doesnt start th game but launching using "launch EXE on Prefix" works.
Here is log:
`Launch Command: WINEESYNC=1 MANGOHUD=1 VKD3D_CONFIG=dxr RADV_PERFTEST=rt VK_ICD_FILENAMES='/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json'  DXVK_LOG_PATH=/home/piotr/dxvk/logs/ DXVK_STATE_CACHE_PATH=/home/piotr/dxvk/state.cache/  MANGOHUD_CONFIG=cpu_temp,gpu_temp,gpu_core_clock,gpu_mem_clock,ram,vram,vulkan_driver,gpu_name,gpu_power,cpu_mhz,wine,engine_version,fps_limit=120 ""/home/piotr/Pobrane/gogdl"" launch "/run/media/piotr/Linux/GOG Games/UnrealGold" 1207658679 --wine /usr/bin/wine --wine-prefix '/home/piotr/.wine' --os windows
        System Info:
        
  Heroic Version: 2.2.6 Oden
  Legendary Version:  0.20.25 Our Benefactors
  OS: Arch KERNEL: 5.17.0-247-tkg-cfs ARCH: x64
  CPU: AMD Ryzen 9 5900X 12-Core Processor @3.7 GOVERNOR: schedutil
  RAM: Total: 67.4 GB Available: 55.3 GB
  GRAPHICS: GPU0: Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] VRAM: 1MB DRIVER:  
  PROTOCOL: wayland
  
        Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"enableEsync": true,
	"maxSharpness": 2,
	"nvidiaPrime": false,
	"offlineMode": true,
	"otherOptions": "MANGOHUD=1 VKD3D_CONFIG=dxr RADV_PERFTEST=rt VK_ICD_FILENAMES='/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json'  DXVK_LOG_PATH=/home/piotr/dxvk/logs/ DXVK_STATE_CACHE_PATH=/home/piotr/dxvk/state.cache/  MANGOHUD_CONFIG=cpu_temp,gpu_temp,gpu_core_clock,gpu_mem_clock,ram,vram,vulkan_driver,gpu_name,gpu_power,cpu_mhz,wine,engine_version,fps_limit=120",
	"savesPath": "",
	"showFps": false,
	"targetExe": "",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/piotr/.wine",
	"wineVersion": {
		"bin": "/usr/bin/wine",
		"name": "Wine Default - wine-7.2 (Staging)"
	},
	"useSteamRuntime": false
}

        Game Log:
        esync: up and running.
002c:fixme:winediag:LdrInitializeThunk wine-staging 7.5 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).``

**Comment by imLinguin** [comment]
> Launch Command: WINEESYNC=1 MANGOHUD=1 VKD3D_CONFIG=dxr RADV_PERFTEST=rt VK_ICD_FILENAMES='/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json' DXVK_LOG_PATH=/home/piotr/dxvk/logs/ DXVK_STATE_CACHE_PATH=/home/piotr/dxvk/state.cache/ MANGOHUD_CONFIG=cpu_temp,gpu_temp,gpu_core_clock,gpu_mem_clock,ram,vram,vulkan_driver,gpu_name,gpu_power,cpu_mhz,wine,engine_version,fps_limit=120 ""/home/piotr/Pobrane/gogdl"" launch "/run/media/piotr/Linux/GOG Games/UnrealGold" 1207658679 --wine /usr/bin/wine --wine-prefix '/home/piotr/.wine' --os windows

Maybe try running that command manually, see what error is thrown and if it's a gogdl issue or not.

**Comment by pppbb** [comment]
`/home/piotr/Pobrane/gogdl launch "/run/media/piotr/Linux/GOG Games/UnrealGold" 1207658679 --wine /usr/bin/wine --wine-prefix '/home/piotr/.wine' --os windows
Namespace(display_version=False, command='launch', path='/run/media/piotr/Linux/GOG Games/UnrealGold', id='1207658679', platform='windows', dont_use_wine=False, wine='/usr/bin/wine', wine_prefix='/home/piotr/.wine', wrapper=None, override_exe=None, token=None)
Launch command: ['/usr/bin/wine', '/run/media/piotr/Linux/GOG Games/UnrealGold/system\\Unreal.exe']
002c:fixme:winediag:LdrInitializeThunk wine-staging 7.5 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
Nie udało się uruchomić aplikacji lub nie ma aplikacji skojarzonej z danym plikiem.
ShellExecuteEx nie powiodło się: Nie znaleziono pliku.
`
Path mismatch should be 'System' instead of 'system'.

**Comment by pppbb** [comment]
When i symlink .../UnrealGold/System/Unreal.exe to .../UnrealGold/system/Unreal.exe the game starts.

**Comment by pppbb** [comment]
> for this issue try latest testing branch: https://github.com/Heroic-Games-Launcher/heroic-gogdl/actions/runs/2060328330

with it i get 'cannot get game info' error and i cant start game or see its page.

**Comment by imLinguin** [comment]
Make sure you marked it as executable

**Comment by pppbb** [comment]
> Make sure you marked it as executable

sorry my mistake
The game runs now without symlinking.

**Comment by wiryfuture** [comment]
fixed
