### ISSUE TITLE
Launcher fails to install games where you can select additional content with legendary

### ISSUE THREAD

**Issue by furokku** [Heroic-Games-Launcher/HeroicGamesLauncher#1427]
### Describe the bug

In the heroic launcher, games like Fortnite do not install correctly, instead hanging on the 'Installing...' text with no ETA. By running the legendary command manually to begin the installation, it appears that it asks you for a comma separated list of additional content, even with the -y option, however it does work, and it seems that this is what causes heroic to simply not install the game.

### Add logs

(22:39:14) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version

(22:39:14) INFO:    [Legendary]:       Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary

(22:39:14) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl

(22:39:14) INFO:    [Backend]:         

Heroic Version: 2.3.6 Brook

Legendary Version:  0.20.26 Dark Energy

OS: Arch KERNEL: 5.18.1-arch1-1 ARCH: x64

CPU: AMD Ryzen 3 2200G with Radeon Vega Graphics @3.5 

RAM: Total: 13.64 GiB Available: 8.84 GiB

GRAPHICS: GPU0: Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] VRAM: 512MB DRIVER:  

PROTOCOL: tty

(22:39:14) WARNING: [Backend]:         Protocol already registered.

(22:39:15) INFO:    [Frontend]:        Refreshing Library

(22:39:15) INFO:    [Legendary]:       Refreshing library...

(22:39:15) INFO:    [Legendary]:       Refreshing Epic Games...

(22:39:16) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list

(22:39:16) DEBUG:   [Legendary]:       Using cached install info

(22:39:17) INFO:    [Legendary]:       Updating game list

(22:39:17) INFO:    [Legendary]:       Game List Updated

(22:39:17) DEBUG:   [Legendary]:       Using cached install info

(22:39:17) DEBUG:   [Legendary]:       Using cached install info

(22:39:17) WARNING: [Backend]:         default is not writable

(22:39:17) INFO:    [Backend]:         Downloaded Winetricks

(22:39:17) INFO:    [Legendary]:       Checking for game updates: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv

(22:39:17) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv

(22:39:19) DEBUG:   [Legendary]:       Using cached install info

(22:39:19) DEBUG:   [Legendary]:       Using cached install info

(22:39:19) INFO:    [Legendary]:       Installing Fortnite with: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary install Fortnite --platform Windows --base-path /mnt/games/heroic --skip-dlcs "--install-tag chunk0 --install-tag chunk10 --install-tag=""" --max-workers 1 -y

(22:39:19) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary install Fortnite --platform Windows --base-path /mnt/games/heroic --skip-dlcs "--install-tag chunk0 --install-tag chunk10 --install-tag=""" --max-workers 1 -y

(22:39:19) DEBUG:   [Legendary]:       Logging to file "/home/furokku/.config/heroic/GamesConfig/Fortnite.log"

(22:39:23) INFO:    [Legendary]:       Found 0 game(s) to update

(22:39:23) INFO:    [Gog]:             Found 0 game(s) to update

### Steps to reproduce

1. Go to any game that allows you to download additional content (e.g. Fortnite)
2. Click on 'Install'
3. See that no game download is ever started.

### Expected behavior

The launcher should start downloading a game, where additional content can be installed at will.

### Screenshots

https://imgur.com/a/rjeixu5

### System Information

- OS: Arch Linux
- Heroic Version 2.3.6

**Comment by flavioislima** [comment]
We will check that. Was working last time I tried. 
As a side note, 
You know that fortnite doesn't work on Linux, right?

**Comment by furokku** [comment]
It does load to the title screen, but crashes on joining a game. Some people have gotten it to work, but I'm moreso using it as an example here.

**Comment by Etaash-mathamsetty** [comment]
> It does load to the title screen, but crashes on joining a game. Some people have gotten it to work, but I'm moreso using it as an example here.

the game does let you chill with ur friends but not actually play

**Comment by WorstLGiver** [comment]
(17:10:44) INFO:    [Legendary]:       Installing Fortnite with: C:\Users\bearo\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary install Fortnite --platform Windows --base-path C:\Users\bearo\Games\Heroic --skip-dlcs "--install-tag chunk0 --install-tag chunk10 --install-tag chunk11 --install-tag chunk11optional --install-tag=""" -y

(17:10:44) DEBUG:   [Legendary]:       Running Legendary command: C:\Users\bearo\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary install Fortnite --platform Windows --base-path C:\Users\bearo\Games\Heroic --skip-dlcs "--install-tag chunk0 --install-tag chunk10 --install-tag chunk11 --install-tag chunk11optional --install-tag=""" -y

(17:10:44) DEBUG:   [Legendary]:       Logging to file "C:\Users\bearo\AppData\Roaming\heroic\GamesConfig\Fortnite.log"

(17:10:45) INFO:    [Backend]:         finished installing

Fortnite.log:

[Core] INFO: Trying to re-use existing login session...
Traceback (most recent call last):
  File "legendary\cli.py", line 3016, in <module>
  File "legendary\cli.py", line 2933, in main
You are about to install Fortnite, this application supports selective downloads.
The following optional packs are available (tag - name):
 * hd_textures - High Resolution Textures
 * lang_cn -   File "legendary\cli.py", line 903, in install_game
  File "legendary\utils\cli.py", line 59, in sdl_prompt
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 16-21: character maps to <undefined>
[15964] Failed to execute script 'cli' due to unhandled exception!

I'm trying to install Fortnite on Windows and encounter the same problem.

**Comment by AverytheFurry** [comment]
My issue linked below is possibly related
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1497

**Comment by Etaash-mathamsetty** [comment]
this is still an issue, looking at the folder in which the game installed, you can see that no files are present, just the folders

**Comment by arielj** [comment]
can you try using the portable build from this PR? https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1481 https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/2505715711

**Comment by Etaash-mathamsetty** [comment]
![image](https://user-images.githubusercontent.com/45927311/174454805-67bda706-92e9-4d32-99a1-80d7c0a12671.png)
seems to work

**Comment by furokku** [comment]
My bad for not looking this over, it seems the issue has been fixed with #1481 .

**Comment by 0x8008** [comment]
As of 22/08/16 and Heroic version 2.4.0 this is still an issue for me.

Update log:
`[cli] INFO: Game needs to be verified before updating, switching to repair mode...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Using existing repair file: C:\Users\bw/.config/legendary\tmp\Fortnite.repair
Traceback (most recent call last):
  File "legendary\cli.py", line 3051, in <module>
  File "legendary\cli.py", line 2968, in main
  File "legendary\cli.py", line 909, in install_game
  File "legendary\utils\cli.py", line 59, in sdl_prompt
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 16-21: character maps to <undefined>
[13752] Failed to execute script 'cli' due to unhandled exception!
You are about to install Fortnite, this application supports selective downloads.
The following optional packs are available (tag - name):
 * hd_textures - High Resolution Textures
 * lang_cn - `

The game downloaded fine using Heroic previously and I played it for a couple of hours, can't patch it today due to a charmap issue...
