### ISSUE TITLE
Failed to import native GOG games

### ISSUE THREAD

**Issue by Lx32** [Heroic-Games-Launcher/HeroicGamesLauncher#1565]
### Describe the bug

I have installed a native GOG games via lutris before GOG support on Heroic and now I want to import it on Heroic. The game is Shadowrun Hong Kong Extended Edition. This is the log of gogdl if launched from the terminal:

> dalmo@pop-os:~$ /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl import /home/dalmo/Giochi/gog/shadowrun-hong-kong/
> Traceback (most recent call last):
>   File "gogdl/cli.py", line 44, in <module>
>   File "gogdl/cli.py", line 40, in main
>   File "gogdl/imports.py", line 60, in get_info
> IndexError: list index out of range
> [15304] Failed to execute script 'cli' due to unhandled exception!

### Add logs

(14:44:18) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(14:44:19) INFO:    [Legendary]:       Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(14:44:19) INFO:    [Gog]:             GOGDL location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl
(14:44:19) INFO:    [Backend]:         

Heroic Version: 2.3.7 Brook
Legendary Version:  0.20.26 Dark Energy
OS: Pop KERNEL: 5.17.15-76051715-generic ARCH: x64
CPU: Intel Gen Intel® Core™ i7-11800H @2.3 GOVERNOR: powersave
RAM: Total: 15.38 GiB Available: 11.02 GiB
GRAPHICS: GPU0: TigerLake-H GT1 [UHD Graphics]  VRAM: 256MB DRIVER:  GPU1: NVIDIA GeForce RTX 3050 Laptop GPU VRAM: 4096MB DRIVER: 515.48.07 
PROTOCOL: x11

(14:44:19) INFO:    [Gog]:             Getting data about the user
(14:44:19) WARNING: [Backend]:         Protocol already registered.
(14:44:19) INFO:    [Gog]:             Saved user data to config
(14:44:20) INFO:    [Frontend]:        Refreshing Library
(14:44:20) INFO:    [Legendary]:       Refreshing library...
(14:44:20) INFO:    [Legendary]:       Refreshing Epic Games...
(14:44:20) INFO:    [Gog]:             Getting GOG library
(14:44:21) INFO:    [Gog]:             Number of library pages: 1
(14:44:21) INFO:    [Gog]:             Saved games data
(14:44:21) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list
(14:44:22) INFO:    [Backend]:         Downloaded Winetricks
(14:44:22) INFO:    [Legendary]:       Updating game list
(14:44:22) INFO:    [Legendary]:       Game List Updated
(14:44:23) INFO:    [Legendary]:       Checking for game updates: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(14:44:23) DEBUG:   [Legendary]:       Running Legendary command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list-installed --check-updates --tsv
(14:44:24) INFO:    [Legendary]:       Found 4 game(s) to update
(14:44:24) INFO:    [Gog]:             Found 0 game(s) to update
(14:44:29) INFO:    [Gog]:             Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1207660413 --token <redacted> --lang=en-US --os windows
(14:44:29) DEBUG:   [Gog]:             Running GOGDL command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1207660413 --token <redacted> --lang=en-US --os windows
(14:44:31) INFO:    [Gog]:             Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1436866438 --token <redacted> --lang=en-US --os windows
(14:44:31) DEBUG:   [Gog]:             Running GOGDL command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1436866438 --token <redacted> --lang=en-US --os windows
(14:44:32) INFO:    [Gog]:             Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1436866438 --token <redacted> --lang=en-US --os windows
(14:44:32) DEBUG:   [Gog]:             Running GOGDL command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1436866438 --token <redacted> --lang=en-US --os windows
(14:44:32) INFO:    [Gog]:             Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1436866438 --token <redacted> --lang=en-US --os windows
(14:44:32) DEBUG:   [Gog]:             Running GOGDL command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1436866438 --token <redacted> --lang=en-US --os windows
(14:44:32) WARNING: [Backend]:         default is not writable
(14:44:32) WARNING: [Backend]:         '/home/dalmo/Giochi/heroic' is not writable
(14:44:34) INFO:    [Gog]:             Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1436866438 --token <redacted> --lang=en-US --os windows
(14:44:34) DEBUG:   [Gog]:             Running GOGDL command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1436866438 --token <redacted> --lang=en-US --os windows
(14:44:34) WARNING: [Backend]:         '/home/dalmo/Giochi/heroic' is not writable
(14:44:41) INFO:    [Gog]:             Importing 1436866438 with: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl import /home/dalmo/Giochi/gog/shadowrun-hong-kong
(14:44:41) DEBUG:   [Gog]:             Running GOGDL command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl import /home/dalmo/Giochi/gog/shadowrun-hong-kong
(14:44:42) INFO:    [Gog]:             Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1436866438 --token <redacted> --lang=en-US --os windows
(14:44:42) DEBUG:   [Gog]:             Running GOGDL command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1436866438 --token <redacted> --lang=en-US --os windows
(14:44:42) ERROR:   [Gog]:             Failed to import 1436866438: 
(14:44:42) INFO:    [Backend]:         imported Shadowrun Hong Kong - Extended Edition
(14:44:42) INFO:    [Frontend]:        Refreshing Library
(14:44:42) INFO:    [Gog]:             Getting GOG library
(14:44:42) INFO:    [Gog]:             Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1436866438 --token <redacted> --lang=en-US --os windows
(14:44:42) DEBUG:   [Gog]:             Running GOGDL command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1436866438 --token <redacted> --lang=en-US --os windows
(14:44:42) INFO:    [Gog]:             Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1436866438 --token <redacted> --lang=en-US --os windows
(14:44:42) DEBUG:   [Gog]:             Running GOGDL command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1436866438 --token <redacted> --lang=en-US --os windows
(14:44:42) INFO:    [Gog]:             Number of library pages: 1
(14:44:42) INFO:    [Gog]:             Saved games data
(14:44:42) INFO:    [Gog]:             Getting game metadata: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1436866438 --token <redacted> --lang=en-US --os windows
(14:44:42) DEBUG:   [Gog]:             Running GOGDL command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl info 1436866438 --token <redacted> --lang=en-US --os windows

### Steps to reproduce

1. Install a native GOG game from Lutris
2. Open Heroic
3. Select the game and click Install
5. Click Import and select the folder of the game
7. See error

### Expected behavior

The game is importend in Heroic

### System Information

- OS [e. g. "Ubuntu"]: Pop_OS! 22.04
- Heroic Version [e. g. 2.1.1]: Heroic 2.3.7

**Comment by imLinguin** [comment]
what's the output of this command 
`/opt/Heroic/resources/app.asar.unpacked/build/bin/linux/gogdl import /home/dalmo/Giochi/gog/shadowrun-hong-kong`

**Comment by Lx32** [comment]
This is the output

```
Traceback (most recent call last):
  File "gogdl/cli.py", line 44, in <module>
  File "gogdl/cli.py", line 40, in main
  File "gogdl/imports.py", line 60, in get_info
IndexError: list index out of range
[20110] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by imLinguin** [comment]
Seems like this is the line which causes it
```py
version_name = target_build["version_name"]
```
However this line shouldn't be executed for Linux native in the first place. I'll investigate it more

**Comment by flavioislima** [comment]
@imLinguin should we keep this opened or this was fixed already ?

**Comment by imLinguin** [comment]
let's keep it open, I'll try to come up with a way to properly import those games

**Comment by arielj** [comment]
@imLinguin is this addressed by the GOG refactor?

**Comment by imLinguin** [comment]
I think we can close this for now, but I won't be surprised if we still fail to import some. We can't reliably import native games (gameinfo file is not consistent and `goggame-*.info` files aren't always present)
