### ISSUE TITLE
Language selector is broken in Settings screen on small resolutions

### ISSUE THREAD

**Issue by arielj** [Heroic-Games-Launcher/HeroicGamesLauncher#1967]
### Describe the bug

When width is less than 850px, the style of the language selector in the settings is broken.

### Add logs

Nothing relevant

### Steps to reproduce

1. Go to settings
2. Resize the window to less than 850px

### Expected behavior

The language selector should not have a broken style

### Screenshots

<img width="806" alt="Screen Shot 2022-10-30 at 8 11 36 PM" src="https://user-images.githubusercontent.com/188464/198906458-93a99046-605b-4fd1-9897-abdb23bd837b.png">

### System Information

- Heroic Version [e. g. 2.1.1]: beta

### Additional information

This style should apply only to the login screen https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/beta/src/frontend/screens/Login/index.css#L47

**Comment by danielheadbang** [comment]
Hello! Maybe this was fixed on some patch? Opening heroic both on flatpak or app image and resizing to the lowest I can (I think about 600px width) doesn't break the styling:

![image](https://user-images.githubusercontent.com/10483127/203650610-32e6f442-48f4-4b08-92a8-19c55b2b335b.png)

Am I missing something?

First time checking these issues and wanted to see if I could contribute :) but I cannot reproduce it on the binaries

Kind regards

**Comment by flavioislima** [comment]
Yes, maybe was fixed in some other PR, Thanks for checking in :)

**Comment by arielj** [comment]
Are you checking the the latest `beta` branch (not the 2.5.0-beta2 release)? I can still see the issue, just tested it
![image](https://user-images.githubusercontent.com/188464/203836266-52a8a05e-4fa3-4d01-9428-9a01e5e6734b.png)

**Comment by danielheadbang** [comment]
Oh, I was checking on the release binaries actually, couldn't get the build instructions to work for me :( but at least I could say this issue does not happen on the actual executables(tested on AppImage and Flatpak).

**Comment by arielj** [comment]
got it, I updated the description to say it's the beta branch, so it's clear it's not the released beta
