### ISSUE TITLE
Zoom resets when switching from FULLSCREEN to WINDOWED and vice versa (Windows 11)

### ISSUE THREAD

**Issue by RaikoWasTaken** [Heroic-Games-Launcher/HeroicGamesLauncher#2156]
### Describe the bug

Zoom, edited through accessibility settings, resets when switching from FULLSCREEN to WINDOWED and vice versa. I need to edit it again for it to go back to normal.
I'm using windows 11
This does not happen when I'm still in the accessibility settings page 

### Add logs

```text
(17:44:51) INFO:    [Connection]:       Connectivity: check-online
(17:44:51) INFO:    [Connection]:       Pinging external endpoints
(17:44:51) INFO:    [Legendary]:        Running command: C:\Users\Raiko\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(17:44:51) INFO:    [Legendary]:        Legendary location: C:\Users\Raiko\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary
(17:44:51) INFO:    [Gog]:              GOGDL location: C:\Users\Raiko\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl
(17:44:51) WARNING: [Backend]:          Protocol already registered.
(17:44:51) INFO:    [Connection]:       Connectivity: online
(17:44:52) INFO:    [Gog]:              Running command: C:\Users\Raiko\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --version
(17:44:53) INFO:    [Backend]:          VCRuntime is installed
(17:44:53) INFO:    [Backend]:          Checking for new Heroic Updates
(17:44:53) INFO:    [Backend]:          Checking for current version changelog
(17:44:53) INFO:    [Frontend]:         Refreshing Library
(17:44:53) INFO:    [Legendary]:        Refreshing library...
(17:44:53) INFO:    [Legendary]:        Refreshing Epic Games...
(17:44:53) INFO:    [Legendary]:        Game list updated, got 5 games & DLCs
(17:44:53) INFO:    [Backend]:          Frontend Ready
(17:44:53) INFO:    [ProtocolHandler]:  received 'heroic://launch/0a2d9f6403244d12969e11da6713137b'
(17:44:53) ERROR:   [Gog]:              Could not get game info for 0a2d9f6403244d12969e11da6713137b, returning empty object. Something is probably gonna go wrong soon
(17:44:53) INFO:    [Backend]:          Launching Fall Guys (0a2d9f6403244d12969e11da6713137b)
(17:44:53) INFO:    [Backend]:          Preventing display from sleep
(17:44:53) INFO:    [Legendary]:        Running command: C:\Users\Raiko\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(17:44:54) INFO:    [Legendary]:        Running command: C:\Users\Raiko\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(17:44:54) INFO:    [Gog]:              Running command: C:\Users\Raiko\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --version
(17:44:58) INFO:    [Backend]:          Starting the Download Queue
(17:44:59) INFO:    [Backend]:          

Heroic Version: 2.5.1 Yamato
Legendary Version:  0.20.31 Dark Energy (hotfix #5)
GOGdl Version: 0.5
OS: Microsoft Windows 11 Home KERNEL: 10.0.22621 ARCH: x64
CPU: AMD Ryzen 7 4800H with Radeon Graphics @2.9 
RAM: Total: 15.37 GiB Available: 10.53 GiB
GRAPHICS: GPU0: NVIDIA GeForce GTX 1650 Ti VRAM: 4096MB DRIVER: 526.98 GPU1: AMD Radeon(TM) Graphics VRAM: 512MB  


(17:45:00) INFO:    [Legendary]:        Running command: C:\Users\Raiko\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary launch 0a2d9f6403244d12969e11da6713137b --json --offline
(17:45:00) INFO:    [Legendary]:        Launching Fall Guys: C:\Users\Raiko\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary launch 0a2d9f6403244d12969e11da6713137b --language it
(17:45:02) INFO:    [Backend]:          Stopped Discord Rich Presence
(17:45:02) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(17:45:02) INFO:    [Frontend]:         Refreshing Library
(17:45:02) INFO:    [Legendary]:        Refreshing library...
(17:45:02) INFO:    [Legendary]:        Game list updated, got 5 games & DLCs
(17:45:17) INFO:    [Backend]:          Exitting to tray instead of quitting
(19:22:05) DEBUG:   [Legendary]:        Using cached install info
(19:22:05) DEBUG:   [Legendary]:        Using cached install info
(19:24:54) INFO:    [Legendary]:        Running command: C:\Users\Raiko\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary --version
(19:24:54) INFO:    [Gog]:              Running command: C:\Users\Raiko\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\gogdl --version
(19:24:54) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Raiko\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(19:24:54) INFO:    [Legendary]:        installed.json updated, refreshing library
(19:24:54) INFO:    [Legendary]:        Abort command "C:\Users\Raiko\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(19:24:54) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Raiko\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(19:24:55) INFO:    [Legendary]:        Abort command "C:\Users\Raiko\AppData\Local\Programs\heroic\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(19:25:06) INFO:    [Backend]:          Checking for current version changelog
```

### Steps to reproduce

1. Go to 'Accessibility Settings'
2. Change the zoom 
3. Go on any other tab

### Expected behavior

The zoom should remain the same

### System Information

Windows 11

**Comment by GenocideStomper** [comment]
Same on Linux when resizing the window.

**Comment by arielj** [comment]
I cannot reproduce this on linux, I don't have windows to test it there.

I tried resizing the window and also going fullscreen/windowed many times using F11, both in the accessibility page and in the library screen.

Is this issue consistent? like it happens 100% of the times? is there any information in the logs? can you try to right click the icon in the tray > debug > check the `console` tab in devtools to see if there's any message

**Comment by GenocideStomper** [comment]
I was able to reproduce the issue immediately on Heroic v. 2.6.2. My zoom setting is set to 70%. As soon as I resize the window, it resets to 100%. When I close and restart Heroic, it's 70% again.

It happens 100% of the time.

The console tab is not saying anything for me. Funnily enough opening the debug panel also resets the zoom level to 100%

**Comment by GenocideStomper** [comment]
I can confirm that just like @wsdfhjxc said, minimizing and unminimizing the window also resets the zoom.

**Comment by itz-me-zappex** [comment]
i have absolutely same issue using heroic 2.7.1, installed from releases via "pacman -U ..."
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.7.1/heroic-2.7.1.pacman

Distro: Arch Linux
Desktop environment: Cinnamon
Session: X11
GPU/Driver: Nvidia GTX 1050 Ti/Proprietary 530.41.03

if I change zoom in "Accessibility" to any value other than 100 (for example, 80%, which looks fine), switch to library or somewhere else and resize/minimize/expand heroic window, zoom setting will reset to default value (100), but settings will still show value which I set (80)

**Comment by itz-me-zappex** [comment]
Heroic 2.9.2, still not fixed

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/85901674/3dc2f332-41e6-439e-b628-fb3471938c23

**Comment by MontblancKupo** [comment]
Happened on windows 10, heroic 2.9.2, and still happening in 2.10.0

**Comment by alterNERDtive** [comment]
Came here to report the same thing, but on Fedora 39. Running on sway/Wayland. Any size change to the Heroic window results in the zoom level resetting back to 100% … unless I currently have the Accessibility settings open m)

**Comment by allora** [comment]
> I cannot reproduce this on linux, I don't have windows to test it there.
> 
> I tried resizing the window and also going fullscreen/windowed many times using F11, both in the accessibility page and in the library screen.
> 
> Is this issue consistent? like it happens 100% of the times? is there any information in the logs? can you try to right click the icon in the tray > debug > check the `console` tab in devtools to see if there's any message

This happens 100% of the time for me in arch. I have bspwm, so cant say what other WMs or DEs experience.

**Comment by alterNERDtive** [comment]
I’m actually still running into this on 2.13.0. Basically _anything_ (even display going into standby) causes Heroic to reset to 100% … unless the “Accessibility” settings are currently opened, then it doesn’t occur.

The funny thing is that the setting does not reset, just the zoom factor itself:
![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/53827887/fb8549e1-0f6e-4bab-8e42-1b28e4073437)
vs actual 60%:
![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/53827887/9b86aa1d-c67c-4689-8dd2-7a11c09653b0)

This is on Fedora 39 / Sway.

**Comment by itz-me-zappex** [comment]
yeah, i still can reproduce that on 2.13.0 as it was on previous versions

**Comment by alterNERDtive** [comment]
Seems fixed with 2.14 :+1:

**Comment by error-0x29A** [comment]
Still happens for me with 2.14.1
While it's not every single time, it is most of the time

Steps to reproduce in my situation (slightly different than the title of this issue, though I can test others if necessary):
1. Open Heroic
2. Go to accessibility area, choose a zoom level other than 100
3. Minimize Heroic to tray (how I have mine set to do when I close the window)
4. Click tray icon to restore Heroic Window
5. Zoom _visually_ resets to 100% even though the slider under accessibility still shows the chosen zoom (like 80% for instance)
6. To get back to 80%, I have to slide it to 100% then back to 80% again for the zoom to re-trigger.
7. These steps generally are infinitely repeatable, with an occasional restore working fine (without the 100% visual reset)

**Comment by alterNERDtive** [comment]
Hmm. I never minimize to tray, did it anyway to try and reproduce. Doesn’t reset for me.

Fedora, Sway 1.9, [Heroic 2.14.1 from copr](https://copr.fedorainfracloud.org/coprs/atim/heroic-games-launcher/).

**Comment by error-0x29A** [comment]
Kubuntu 22.04, Cinnamon for DE, no global scaling set in display settings
Also happened on default DE (KDE) when I had it installed

Using **heroic_2.14.1_amd64.deb** from releases page

**Comment by alterNERDtive** [comment]
Well, minimizing to tray did not exhibit the bug … but generally it seems to be back with 2.14.1 :-/

**Comment by 666xan666** [comment]
Flatpak 2.15.1 - same issues on Mint 22.

**Comment by alterNERDtive** [comment]
Small update: a) still happens on 2.15.2 and b) you can trigger it by leaving the launcher open when sending the PC to standby. Wake it up, zoom level resets.

**Comment by 666xan666** [comment]
Flatpak 2.15.2 - nope. Issue still exists.  Even TWO now:
1. Opening application: my zoom factor is set to 100% even though it was set at different value at the beginning or after closing the application.
2. Changing zoom size resets to 100% after window minimization.

Video uploaded here: https://file.io/bKB87QjkkuvD

**Comment by 666xan666** [comment]
Issue marked here as SOLVED https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3325 but it is NOT SOLVED at all Gents. Zoom level still resetting to 100% over and over and over again. No matter what I do or not to [having only HGL open]. Will this be solved? Issue is abnormally annoying on 4k monitor.

**Comment by arielj** [comment]
> Issue marked here as SOLVED #3325 but it is NOT SOLVED at all Gents. Zoom level still resetting to 100% over and over and over again. No matter what I do or not to [having only HGL open]. Will this be solved? Issue is abnormally annoying on 4k monitor.

Can you try this flatpak from the main development branch? https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/12737990547

there was a new fix merged but not released yet, some users confirmed the new fix works, so it should be solved by next relesae

**Comment by alterNERDtive** [comment]
This is still happening for me on 2.19.1, btw.

(specifically when on a game’s details page)

**Comment by alterNERDtive** [comment]
I just clicked the “Wine Manager” tab (no resizing the window involved), and BAM, zoom reset :<
