### ISSUE TITLE
heroic_2.6.1_amd64.deb Not connecting to GOG

### ISSUE THREAD

**Issue by Texashuman** [Heroic-Games-Launcher/HeroicGamesLauncher#2422]
### Describe the bug

I am not able to download my games from GOG
Doesn't display download or install size.
If I click install it sits with the circle running round and round.

### Add logs

```text
(17:22:01) INFO:    [Connection]:       Connectivity: check-online
(17:22:01) INFO:    [Connection]:       Pinging external endpoints
(17:22:01) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(17:22:01) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(17:22:01) INFO:    [Gog]:              GOGDL location: /home/daviwaynedisney/gogdl
(17:22:01) INFO:    [Gog]:              GOGDL location: /home/daviwaynedisney/gogdl
(17:22:02) WARNING: [Backend]:          Protocol already registered.
(17:22:02) INFO:    [Gog]:              Running command: /home/daviwaynedisney/gogdl --version
(17:22:02) INFO:    [Connection]:       Connectivity: online
(17:22:02) INFO:    [Gog]:              Getting data about the user
(17:22:02) INFO:    [Gog]:              Refreshing access_token
(17:22:02) INFO:    [Backend]:          

Heroic Version: 2.6.1 Trafalgar Law
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 

Electron Version: 22.2.0
Chrome Version: 108.0.5359.215
NodeJS Version: 16.17.1

OS: Debian GNU/Linux KERNEL: 5.10.153-20434-g98da1eb2cf9d ARCH: x64
CPU: Intel Gen Intel® Core™ i5-1235U @2.5 
RAM: Total: 6.35 GiB Available: 6 GiB
GRAPHICS: 
PROTOCOL: 

(17:22:02) INFO:    [Backend]:          Loading Screen Ready
(17:22:02) INFO:    [Frontend]:         Refreshing Library
(17:22:02) INFO:    [Legendary]:        Refreshing library...
(17:22:02) INFO:    [Legendary]:        Refreshing Epic Games...
(17:22:02) INFO:    [Gog]:              Refreshing access_token
(17:22:02) INFO:    [Legendary]:        Game list updated, got 4 games & DLCs
(17:22:02) INFO:    [Backend]:          Frontend Ready
(17:22:02) INFO:    [Backend]:          Checking for new Heroic Updates
(17:22:02) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(17:22:02) INFO:    [Backend]:          Checking for current version changelog
(17:22:02) INFO:    [Gog]:              Token refreshed successfully
(17:22:02) INFO:    [Gog]:              Token refreshed successfully
(17:22:02) INFO:    [Gog]:              Getting GOG library
(17:22:03) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(17:22:03) INFO:    [Gog]:              Saved user data to config
(17:22:03) INFO:    [Gog]:              Number of library pages: 1
(17:22:03) INFO:    [Gog]:              Saved games data
(17:22:04) INFO:    [Winetricks]:       Downloading Winetricks
(17:22:07) INFO:    [Backend]:          Starting the Download Queue
(17:25:16) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Darklands
(17:25:16) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Darklands
(17:25:16) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Darklands
(17:25:16) INFO:    [Gog]:              Getting game metadata: /home/daviwaynedisney/gogdl info 1207658972 --token <redacted> --lang=en-US --os linux
(17:25:16) INFO:    [Gog]:              Getting game metadata: /home/daviwaynedisney/gogdl info 1207658972 --token <redacted> --lang=en-US --os linux
(17:25:16) INFO:    [Gog]:              Getting game metadata: /home/daviwaynedisney/gogdl info 1207658972 --token <redacted> --lang=en-US --os linux
(17:25:16) INFO:    [Gog]:              Getting game metadata: /home/daviwaynedisney/gogdl info 1207658972 --token <redacted> --lang=en-US --os linux
(17:25:17) WARNING: [Gog]:              Failed to get Install Info for 1207658972 using linux as platform, returning empty object
(17:25:17) WARNING: [Gog]:              Failed to get Install Info for 1207658972 using linux as platform, returning empty object
(17:25:17) WARNING: [Gog]:              Failed to get Install Info for 1207658972 using linux as platform, returning empty object
(17:25:17) WARNING: [Gog]:              Failed to get Install Info for 1207658972 using linux as platform, returning empty object
(17:26:16) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Curse of the Azure Bonds
(17:26:16) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Curse of the Azure Bonds
(17:26:16) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Curse of the Azure Bonds
(17:26:16) INFO:    [Gog]:              Getting game metadata: /home/daviwaynedisney/gogdl info 1432642138 --token <redacted> --lang=en-US --os linux
(17:26:16) INFO:    [Gog]:              Getting game metadata: /home/daviwaynedisney/gogdl info 1432642138 --token <redacted> --lang=en-US --os linux
(17:26:16) INFO:    [Gog]:              Getting game metadata: /home/daviwaynedisney/gogdl info 1432642138 --token <redacted> --lang=en-US --os linux
(17:26:16) INFO:    [Gog]:              Getting game metadata: /home/daviwaynedisney/gogdl info 1432642138 --token <redacted> --lang=en-US --os linux
(17:26:16) WARNING: [Gog]:              Failed to get Install Info for 1432642138 using linux as platform, returning empty object
(17:26:16) WARNING: [Gog]:              Failed to get Install Info for 1432642138 using linux as platform, returning empty object
(17:26:16) WARNING: [Gog]:              Failed to get Install Info for 1432642138 using linux as platform, returning empty object
(17:26:16) WARNING: [Gog]:              Failed to get Install Info for 1432642138 using linux as platform, returning empty object
(17:26:55) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Hillsfar
(17:26:55) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Hillsfar
(17:26:55) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Hillsfar
(17:26:55) INFO:    [Gog]:              Getting game metadata: /home/daviwaynedisney/gogdl info 1432640506 --token <redacted> --lang=en-US --os linux
(17:26:55) INFO:    [Gog]:              Getting game metadata: /home/daviwaynedisney/gogdl info 1432640506 --token <redacted> --lang=en-US --os linux
(17:26:55) INFO:    [Gog]:              Getting game metadata: /home/daviwaynedisney/gogdl info 1432640506 --token <redacted> --lang=en-US --os linux
(17:26:55) INFO:    [Gog]:              Getting game metadata: /home/daviwaynedisney/gogdl info 1432640506 --token <redacted> --lang=en-US --os linux
(17:26:55) WARNING: [Gog]:              Failed to get Install Info for 1432640506 using linux as platform, returning empty object
(17:26:55) WARNING: [Gog]:              Failed to get Install Info for 1432640506 using linux as platform, returning empty object
(17:26:55) WARNING: [Gog]:              Failed to get Install Info for 1432640506 using linux as platform, returning empty object
(17:26:55) WARNING: [Gog]:              Failed to get Install Info for 1432640506 using linux as platform, returning empty object
(17:27:22) INFO:    [Frontend]:         Refreshing Library
(17:27:22) INFO:    [Legendary]:        Refreshing library...
(17:27:22) INFO:    [Legendary]:        Refreshing Epic Games...
(17:27:22) INFO:    [Legendary]:        Game list updated, got 4 games & DLCs
(17:27:22) INFO:    [Gog]:              Getting GOG library
(17:27:23) INFO:    [Gog]:              Number of library pages: 1
(17:27:23) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(17:27:24) INFO:    [Gog]:              Saved games data
```

### Steps to reproduce

1. Go to '.Open The launcher..'
2. Click on '..any GOG game.'
3. Scroll down to '...'
4. See error No error just nothing happens

### Expected behavior

game should download

### Screenshots

![image](https://user-images.githubusercontent.com/123138497/216795033-26908476-b9c1-447d-9365-0331d387ce12.png)

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: 
![image](https://user-images.githubusercontent.com/123138497/216795049-3e917b63-e840-4014-a5ba-277e81a4e84e.png)

### Additional information

Where do I find the >>>> Latest stable version of Heroic is 2.6.2. Please, update Heroic before reporting a bug if you have an older version.
All I can find is 2.6.1

**Comment by flavioislima** [comment]
Yes, we fixed this hug already but we had some issues with the release and we will have to postpone it until tomorrow.

**Comment by Texashuman** [comment]
I got the release and still cannot get my games.    (13:29:54) INFO:    [Connection]:       Connectivity: check-online
(13:29:54) INFO:    [Connection]:       Pinging external endpoints
(13:29:54) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary --version
(13:29:54) INFO:    [Legendary]:        Legendary location: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary
(13:29:54) INFO:    [Gog]:              GOGDL location: /home/daviwaynedisney/gogdl
(13:29:54) INFO:    [Gog]:              GOGDL location: /home/daviwaynedisney/gogdl
(13:29:54) WARNING: [Backend]:          Protocol already registered.
(13:29:54) INFO:    [Gog]:              Running command: /home/daviwaynedisney/gogdl --version
(13:29:54) INFO:    [Connection]:       Connectivity: online
(13:29:54) INFO:    [Gog]:              Getting data about the user
(13:29:54) INFO:    [Backend]:          

Heroic Version: 2.6.2 Trafalgar Law
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 

Electron Version: 22.2.0
Chrome Version: 108.0.5359.215
NodeJS Version: 16.17.1

OS: Debian GNU/Linux KERNEL: 5.10.153-20434-g98da1eb2cf9d ARCH: x64
CPU: Intel Gen Intel® Core™ i5-1235U @2.5 
RAM: Total: 6.35 GiB Available: 5.64 GiB
GRAPHICS: 
PROTOCOL: 

(13:29:54) INFO:    [Backend]:          Loading Screen Ready
(13:29:54) INFO:    [Frontend]:         Refreshing Library
(13:29:54) INFO:    [Legendary]:        Refreshing library...
(13:29:54) INFO:    [Legendary]:        Refreshing Epic Games...
(13:29:54) INFO:    [Legendary]:        Game list updated, got 4 games & DLCs
(13:29:54) INFO:    [Gog]:              Getting GOG library
(13:29:54) INFO:    [Backend]:          Frontend Ready
(13:29:54) INFO:    [Backend]:          Checking for new Heroic Updates
(13:29:54) INFO:    [Backend]:          Checking for current version changelog
(13:29:55) INFO:    [Backend]:          AreWeAntiCheatYet data downloaded
(13:29:55) INFO:    [Gog]:              Saved user data to config
(13:29:55) INFO:    [Gog]:              Number of library pages: 1
(13:29:55) INFO:    [Legendary]:        Running command: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(13:29:56) INFO:    [Gog]:              Saved games data
(13:29:56) INFO:    [Legendary]:        Checking for game updates: /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party
(13:29:56) INFO:    [Winetricks]:       Downloading Winetricks
(13:29:57) WARNING: [Legendary]:        Failed to parse games from /home/daviwaynedisney/.config/legendary/installed.json with: Error: ENOENT: no such file or directory, open '/home/daviwaynedisney/.config/legendary/installed.json'
    at Object.openSync (node:fs:594:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.readFileSync (node:fs:462:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
    at R.listUpdateableGames (/opt/Heroic/resources/app.asar/build/electron/main.6ace4a2c.js:56:9290)
    at async /opt/Heroic/resources/app.asar/build/electron/main.6ace4a2c.js:184:3970

    at async node:electron/js2c/browser_init:2:97553
(13:29:57) INFO:    [Legendary]:        Found 0 games to update
(13:29:57) INFO:    [Gog]:              Found 0 game(s) to update
(13:29:59) INFO:    [Backend]:          Starting the Download Queue
(13:30:01) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Master of Orion 2
(13:30:01) INFO:    [Gog]:              Getting game metadata: /home/daviwaynedisney/gogdl info 1207661633 --token <redacted> --lang=en-US --os windows
(13:30:01) INFO:    [Gog]:              Getting game metadata: /home/daviwaynedisney/gogdl info 1207661633 --token <redacted> --lang=en-US --os windows
(13:30:01) INFO:    [Gog]:              Getting game metadata: /home/daviwaynedisney/gogdl info 1207661633 --token <redacted> --lang=en-US --os windows
(13:30:01) INFO:    [Gog]:              Getting game metadata: /home/daviwaynedisney/gogdl info 1207661633 --token <redacted> --lang=en-US --os windows
(13:30:01) WARNING: [Gog]:              Failed to get Install Info for 1207661633 using windows as platform, returning empty object
(13:30:01) WARNING: [Gog]:              Failed to get Install Info for 1207661633 using windows as platform, returning empty object
(13:30:01) WARNING: [Gog]:              Failed to get Install Info for 1207661633 using windows as platform, returning empty object
(13:30:01) WARNING: [Gog]:              Failed to get Install Info for 1207661633 using windows as platform, returning empty object
(13:30:06) INFO:    [Gog]:              Getting game metadata: /home/daviwaynedisney/gogdl info 1207661633 --token <redacted> --lang=en-US --os windows
(13:30:06) DEBUG:   [Backend]:          {"free":32585953280,"diskSize":42949672960,"message":"30.35 GiB / 40 GiB","validPath":true}
(13:30:06) WARNING: [Gog]:              Failed to get Install Info for 1207661633 using windows as platform, returning empty object

**Comment by imLinguin** [comment]
Try removing alternative gogdl binary you selected from Heroic Settings > Advanced.  
And use the built in one

**Comment by Texashuman** [comment]
I suspected that could be needed but, so far no search has produced the magic formula to do it.

I can copy and paste or transcribe commands but I am terminally illiterate.

**Comment by imLinguin** [comment]
You don't need to do anything in terminal, just remove the path from the input in Heroic settings and you should be good to go.

**Comment by Texashuman** [comment]
Ok, Got the Launcher to work. Now to get the games to play in full screen.

**Comment by arielj** [comment]
@Texashuman is this working fine now? if not can you try with Heroic 2.7?

**Comment by Texashuman** [comment]
Ok. Downloaded and installed 2.7. So far it won't even launch at all.

**Comment by arielj** [comment]
is this still an issue with 2.9.2?

**Comment by Texashuman** [comment]
> is this still an issue with 2.9.2?

I have no idea.. I just tried the Launcher on my Chromebook and it didn't work at all. I had been getting the launcher open. Getting connected to GOG and EPIC, but I couldn't get the GOG games to play because of an issue with the way GOG has implemented DOS BOX.

When I get a chance I will delete my LINUX partition on the Chromebook and start over.

**Comment by flavioislima** [comment]
> > is this still an issue with 2.9.2?
> 
> I have no idea.. I just tried the Launcher on my Chromebook and it didn't work at all. I had been getting the launcher open. Getting connected to GOG and EPIC, but I couldn't get the GOG games to play because of an issue with the way GOG has implemented DOS BOX.
> 
> When I get a chance I will delete my LINUX partition on the Chromebook and start over.

Sorry but we do not officially support Chromebooks. 
A tip is for you to use Flatpak instead of .deb on it, but it is not guaranteed to work. You can always ask for help on not supported systems on our Discord, but check on our README the operating systems we support officialy.
