### ISSUE TITLE
New update causes message on mac to say heroic is damaged and cant be opened

### ISSUE THREAD

**Issue by CoolDog22YT** [Heroic-Games-Launcher/HeroicGamesLauncher#2681]
### Describe the bug

Whenever i try and and open heroic thereis a messsage that heroic is damage and cannot be opened. This is only with the new update(2.7.1).

### Add logs

```text
None because it is a download.
```

### Steps to reproduce

1. Go to 'Github page'
2. Click on 'click on 2.7.1 and dowload then open after you finish the download'
3.. See error

### Expected behavior

The app opens and lets you start the app. You should see the game page with all your pages. 

### Screenshots

<img width="1440" alt="Screenshot 2023-05-05 at 8 03 37 PM" src="https://user-images.githubusercontent.com/29024047/236587056-cf392a51-c019-4fed-a908-5d8e8eeda5f6.png">

### Heroic Version

Latest Stable

### System Information

- OS MacOs 13.4 Beta (22F5059b)

### Additional information

I am on a macos beta which could be causing the problem. I have had this problem both while auto updating and just doing a whole reinstall of the app

**Comment by haneefmubarak** [comment]
Bug reproduces on Monterey 12.1 x64

**Comment by arielj** [comment]
@flavioislima can it be that something failed with the signing of the binary? I remember this was fixed

or is the `xattr -r -d com.apple.quarantine /Applications/Heroic.app` command still needed?

**Comment by flavioislima** [comment]
Yes, the command should not be needed after the signing, I will rebuild it on my Mac and reupload it later today.

**Comment by asmaloney** [comment]
FWIW I had the same problem (macOS 12.6.5) and the `xattr` quarantine  command fixed it.

**Comment by flavioislima** [comment]
I updated the binaries and they should be working now.

**Comment by stradicat** [comment]
The problem persists on Intel Macs (running Monterey and Ventura here), but running `sudo xattr -cr /Applications/Heroic.app` after installation fixed it for me.
