### ISSUE TITLE
Heroic freezing while downloading big games.

### ISSUE THREAD

**Issue by cronyakatsuki** [Heroic-Games-Launcher/HeroicGamesLauncher#277]
**Describe the bug**
Heroic freezes while downloading big games if focus is not on the launcher.

**To Reproduce**

1. Choose any bigger game 
2. Start downloading
3. Do anything else
4. Come back to it after a couple of mins

**Expected behavior**
Heroic not freezing

**Screenshots**
![Imgur](https://i.imgur.com/uMxbIfN.png)

**Desktop (please complete the following information):**

- OS: Manjaro
- Version: Testing Repos
- Game: big games
- Wine/Proton version:

**Additional context**
Legendary still downloads games in the background but the UI is frozen.

**Comment by GM-Script-Writer-62850** [comment]
Able to confirm using GTA5, UI progress broke at 39.12% and claimed the download was canceled, network activity shows it still downloading at ~120Mbps
the UI is not frozen, just the progress meter

**Comment by adityaruplaha** [comment]
Can you please upload the Legendary log? I'll take a look at what's happening. Probably an issue with how we parse logfiles to get the progress.

**Comment by GM-Script-Writer-62850** [comment]
where do i find said log file?
all i see are json files in ~/.config/legendary

**Comment by adityaruplaha** [comment]
I think it will be the same as the installation log in GamesConfig. I think Latest Log will take you there.

**Comment by GM-Script-Writer-62850** [comment]
If something useful was there it is been overwritten

**Comment by adityaruplaha** [comment]
Oh well, there's not much I can do without the log. If anyone faces the issue again, please uploadb the log.

Good thing this part I plan to refactor anyways.

**Comment by GM-Script-Writer-62850** [comment]
what could be happening is the ui is reading the file while it is in the process of being written to and when that happens it causes a error or unexpected data string, the easy solution is to catch the error and try it again after 100 ms

if you are getting progress by reading a log file that is my guess to the issue

**Comment by flavioislima** [comment]
I also believe that this can be the issue, but this is quite a difficult bug for me to replicate, I could not so far. From time to time someone complains about this but this never happened to me. I don't know if its because I have a fast internet, but even downloading GTAV that can take, for me, around 1 or 2 hours, this doesn't happen. Even if I put the app on background or on tray.

We might think about a different way of reading/writing the log, or gather the progress and might fix, or not, this issue.

**Comment by flavioislima** [comment]
About Fortnite:
1: it doesnt work on Linux so you can just drop it.
2: it uses selective download that is something that Heroic still does not support since there are only two games so far that uses it: Fortnite and Cyberpunk 2077, and this is a lot of effort to implement on our side.

About the other one. Try putting that command on terminal, that starts with `/opt` until `-y`.
You can use it to download fortnite if you really want it.

**Comment by mrbean457** [comment]
ok thanks i will try that.

**Comment by tridoxx** [comment]
I have the same problem, but the game seems to keep downloading in the background, so I left it like that all night and in the morning I canceled it and if it was downloaded

**Comment by cronyakatsuki** [comment]
Update on this topic. It seems like it was a ram problem, atleast it seems to me because after I got more ram inside my latop it hasn't happened anymore. Either that or it has been fixed in previous releases.

**Comment by flavioislima** [comment]
@tridoxx  @mrbean457 can you still experience this issue with latest version (1.6.1) ?

**Comment by flavioislima** [comment]
If yes, can you guys try this test version:
https://drive.google.com/file/d/1tfyVw4ytzHCjlC3fuOaQrt_V8ak-y4cr/view?usp=sharing

**Comment by adityaruplaha** [comment]
Duplicate of #195.

Please continue discussion here.
