### ISSUE TITLE
Amazon Games not launching

### ISSUE THREAD

**Issue by LiamDawe** [Heroic-Games-Launcher/HeroicGamesLauncher#2901]
### Describe the bug

Testing out Amazon Games in 2.9 on Fedora KDE 38, games won't seem to launch.

Tested:

Roguebook
Baldur's Gate II

Both with different Wine-GE and GE-Proton, neither launch.

### Add logs

https://gist.github.com/LiamDawe/aca8085bbb769f53c43265c01ea4333c

### Steps to reproduce

Trying it on Fedora with Flatpak.

### Expected behavior

The games to launch

### Heroic Version

Latest Stable

### System Information

Fedora KDE 38
NVIDIA 2080 Ti

**Comment by LiamDawe** [comment]
Tried enabling gamemode as suggested in Discord, and games still not launching: https://gist.github.com/LiamDawe/bb13ada52df6b6cc69e3c4c7d0a37ac6

**Comment by Goggo66** [comment]
I can partially confirm.

Tried "Banners of Ruin" (on Kubuntu 23.04).

Game does start with the standard wine installation coming with the distribution.
Game does **not** start with any proton version. Instead, the steam client window opens.

**Comment by leillo1975** [comment]
I have the same problem with WRC9 and Rogue Squadron 3D. If I execute the game with wine directly on his folder, without heroic and using the in-system installed wine, they work as spected. 

I use Ubuntu 22.04, and I tried with the last Wine Stagin, Proton 8.0 and Proton-GE

**Comment by Nazario-DApote-Kyklos** [comment]
I tried Blasfemous and Metal Slug 4 on Steam Deck and either failed to start.

**Comment by nonoche2** [comment]
I'm on macOS and Amazon Games do not launch with heroic (log error says "WARNING: [Backend] could not determine system info"
Launching amazon games installed with Heroic with Crossover works fine.

**Comment by Nazario-DApote** [comment]
I tries Blasfemous and Metal Slug 4 on SteamDeck and either didn't start at all.
The same games installed by Lutris work fines.

**Comment by aureliensoria** [comment]
Hello !
Same issue on my side with Q.U.B.E 2 on POP!_OS.

**Comment by oldlamps** [comment]
I can confirm that this is also happening for me in both the Flatpak and AUR install of Heroic. Changing to system wine, or any other version has the same result predictably since the issue is that nile  is instantly closing once called

`LD_PRELOAD= WINEPREFIX=/home/oldlamps/Games/Heroic/Prefixes/Amazon WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 ORIG_LD_LIBRARY_PATH= XDG_CONFIG_HOME=/home/oldlamps/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile launch --override-exe "/home/oldlamps/Games/Heroic/Day of the Tentacle/Dott.exe" --wine /usr/bin/wine --wrapper --wine-prefix /home/oldlamps/Games/Heroic/Prefixes/Amazon e6fe2ec9-719f-443c-be30-61e3992401c9`

Maybe the long game ID being called is incorrect?

**Comment by nonoche2** [comment]
> I'm on macOS and Amazon Games do not launch with heroic (log error says "WARNING: [Backend] could not determine system info" (tried with a dozen titles)
> Launching amazon games installed with Heroic from Crossover works fine.

still getting the same issue with version 2.9.1

**Comment by leillo1975** [comment]
With WRC9 I have the same problem. Running with system installed wine without heroic works, but with heroic I have a crash report popup:
![Captura de pantalla de 2023-07-27 00-00-17](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/551821/4c87f15d-cc18-400f-b9f0-f00c1f5b85a5)

**Comment by duncreg** [comment]
I believe some Amazon Games require their launcher to be running because of DRM.

**Comment by upmferraz** [comment]
yep, same
bash: /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile: No such file or directory

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallVkd3d": true,
	"preferSystemLibs": false,
	"enableEsync": true,
	"enableFSR": true,
	"enableFsync": false,
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"showFps": false,
	"useGameMode": false,
	"language": "",
	"wineVersion": {
		"bin": "/home/deck/.local/share/Steam/steamapps/common/Proton - Experimental/proton",
		"name": "Proton - Proton - Experimental",
		"type": "proton"
	},
	"winePrefix": "/home/deck/Games/Heroic/.prefixes/Star Wars The Force Unleashed",
	"wineCrossoverBottle": ""
}

Game launched at: Thu Jul 27 2023 00:31:13 GMT+0100 (Irish Standard Time)

System Info:
Heroic Version: 2.9.1 Boa Hancock
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.3
Nile Version: 1.0.0 Jonathan Joestar

Electron Version: 24.4.1
Chrome Version: 112.0.5615.204
NodeJS Version: 18.14.0

OS: Freedesktop SDK KERNEL: 5.13.0-valve36-1-neptune ARCH: x64
CPU: AMD Custom APU 0405 @3.11 GOVERNOR: schedutil
RAM: Total: 13.49 GiB Available: 10.28 GiB
GRAPHICS: GPU0: VanGogh [AMD Custom GPU 0405] VRAM: 512MB 
PROTOCOL: x11

Launch Command: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH="/home/deck/Games/Heroic/.prefixes/Star Wars The Force Unleashed" STEAM_COMPAT_INSTALL_PATH="/home/deck/Games/Heroic/Star Wars The Force Unleashed" WINE_FULLSCREEN_FSR=1 WINE_FULLSCREEN_FSR_STRENGTH=2 PROTON_NO_FSYNC=1 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId="heroic-Star Wars The Force Unleashed" PROTON_LOG_DIR=/home/deck/.var/app/com.heroicgameslauncher.hgl /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile launch --no-wine --wrapper " '/home/deck/.local/share/Steam/steamapps/common/Proton - Experimental/proton' run" --wine-prefix "/home/deck/Games/Heroic/.prefixes/Star Wars The Force Unleashed" amzn1.adg.product.2bf7606d-d642-46ac-aae4-bb60175cfd2d

Game Log:
INFO [CLI]:	 Searching for amzn1.adg.product.2bf7606d-d642-46ac-aae4-bb60175cfd2d
INFO [LAUNCHER]:	 Launching
esync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
All processes exited

**Comment by imLinguin** [comment]
the DRM is deprecated since they rebranded Twitch App to Amazon Games, it's unlikely to encounter any game requiring it

Most issues reported here are now fixed in 2.9.

As to WRC 9 @leillo1975 this looks like a wine configuration issue, for assistance regarding it please use our Discord server

**Comment by leillo1975** [comment]
> I believe some Amazon Games require their launcher to be running because of DRM.

I don't think it's a problem with the Launcher or DRM. Installing the game with the system-installed Wine (without heroic), works correctly if I run the game executable directly.

**Comment by leillo1975** [comment]
> As to WRC 9 @leillo1975 this looks like a wine configuration issue, for assistance regarding it please use our Discord server

I just created a new thread:
https://discord.com/channels/812703221789097985/1019893397340835840/threads/1134028024346583131

**Comment by imLinguin** [comment]
I believe this is solved. @nonoche2 your issue seems unrelated to this, maybe create separate issue with more context

**Comment by deKay01** [comment]
Still an issue for me in 2.9.1 on a Steam Deck. Tried about 20 Amazon games, none load. Example error log:

`Game Settings: {
	"autoInstallDxvk": false,
	"autoInstallVkd3d": false,
	"preferSystemLibs": false,
	"enableEsync": true,
	"enableFsync": true,
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"showFps": false,
	"useGameMode": false,
	"language": "",
	"wineVersion": {
		"bin": "/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/proton",
		"name": "Proton - Proton 7.0",
		"type": "proton"
	},
	"winePrefix": "/home/deck/Games/Heroic/Prefixes/3 Count Bout",
	"wineCrossoverBottle": ""
}

Game launched at: Thu Jul 27 2023 19:42:11 GMT+0100 (Irish Standard Time)

System Info:
Heroic Version: 2.9.1 Boa Hancock
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.3
Nile Version: 1.0.0 Jonathan Joestar

Electron Version: 24.4.1
Chrome Version: 112.0.5615.204
NodeJS Version: 18.14.0

OS: Freedesktop SDK KERNEL: 5.13.0-valve36-1-neptune ARCH: x64
CPU: AMD Custom APU 0405 @3.33 GOVERNOR: schedutil
RAM: Total: 14.47 GiB Available: 11.68 GiB
GRAPHICS: GPU0: VanGogh [AMD Custom GPU 0405] VRAM: 512MB
PROTOCOL: x11

Launch Command: STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH="/home/deck/Games/Heroic/Prefixes/3 Count Bout" STEAM_COMPAT_INSTALL_PATH="/home/deck/Games/Heroic/3 Count Bout" WINE_FULLSCREEN_FSR=0 STEAM_COMPAT_APP_ID=0 SteamAppId=0 SteamGameId="heroic-3 Count Bout" PROTON_LOG_DIR=/home/deck/.var/app/com.heroicgameslauncher.hgl /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/nile launch --no-wine --wrapper " '/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/proton' run" --wine-prefix "/home/deck/Games/Heroic/Prefixes/3 Count Bout" amzn1.adg.product.6463784a-5716-481d-b006-e19c26e9214c

Game Log:
INFO [CLI]:	 Searching for amzn1.adg.product.6463784a-5716-481d-b006-e19c26e9214c
INFO [LAUNCHER]:	 Launching
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API FAIL] SteamAPI_Init() failed
All processes exited `

**Comment by Nocccer** [comment]
Use wine-ge from our wine manager. Enable dxvk and vkd3d in gane settings. Disable esync and fsync aswell till the game launches. Proton is meant for steam and steam only. So wine-ge is the best choice

**Comment by deKay01** [comment]
That worked! Not had any issues with Proton on Heroic with Epic and GoG games but Amazon ones? But yeah, working now, thanks.

**Comment by Nocccer** [comment]
If proton does not work always use wine-ge to debug gives also alot of logs aswell to see problems like missing libs

**Comment by Goggo66** [comment]
The recent [fix](https://github.com/imLinguin/nile/commit/f5f3b96f6483c59cfc646afbda6e97cb0bd94778) in nile fixes my issues when running games with proton. It is not part of Heroic v2.9.1, as far as I can see.

**Comment by Nazario-DApote** [comment]
I tried the new version 2.9.1 but it doesn't solve the problem. Amazon games still won't start.

**Comment by deKay01** [comment]
> I tried the new version 2.9.1 but it doesn't solve the problem. Amazon games still won't start.

See above - [Nocccer](https://github.com/Nocccer) suggested using Wine-GE instead of Proton, and that works for me.

**Comment by Nazario-DApote** [comment]
> > I tried the new version 2.9.1 but it doesn't solve the problem. Amazon games still won't start.
> 
> See above - [Nocccer](https://github.com/Nocccer) suggested using Wine-GE instead of Proton, and that works for me.

Thanks with Wine-GE works for me.
