### ISSUE TITLE
Error: spawn free EACCES

### ISSUE THREAD

**Issue by Agotech22** [Heroic-Games-Launcher/HeroicGamesLauncher#3243]
### Describe the bug

When I open the "log in" menu, i get an error: Error: spawn free EACCES. It tells me to report it as well, which is what I'm doing. I really want to play a game I've been waiting to play for a long time, and this is in my way. I can log on to GOG but I need Epic Games. Can anyone please help?

### Add logs

```text
Error:

A uncaught exception occured:
Error: spawn free EACCES
Report the exception on our Github repository.
```

### Steps to reproduce

1. Go to Library
2. Click on Log in
3. Log in to Epic Games

### Expected behavior

I expected to be able to log in and play some games with my friends. I was super excited :(

### Screenshots

![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/151410056/45885651-8f2a-477b-8766-1774bf45bc8c)

### Heroic Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]:

**Comment by arielj** [comment]
Are you using Heroic installed as a Snap package?

If so, try installing it as a .deb or .appimage or flatpak, the error looks like something that should be fixed in 2.10.0 but you still have it for some reason

**Comment by Agotech22** [comment]
I've installed it through the Ubuntu Software Store if that is what you mean.

At the corner of my screen, my version is 2.10.0, just for reference. I don't want to install from other sources other than the Software Center and I read in another GitHub thread that the was "legendary archive file" which you could open inside the launcher and it should fix the problem. Link: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/1789#issuecomment-1241160868

Thanks!

**Comment by carnival4736** [comment]
Probably related, got this from "epic alternative login method" [snap, 2.10.0]
```
An error has occurred! Try to Logout and Login on your Epic account.
Traceback (most recent call last):
File "legendary/cli.py", line 3148, in <module>
File "legendary/cli.py", line 3032, in main
File "legendary/cli.py", line 48, in setup_threaded_logging
File "multiprocessing/context.py", line 103, in Queue
File "multiprocessing/queues.py", line 43, in __init__
File "multiprocessing/context.py", line 68, in LockFile "multiprocessing/synchronize.py", line 162, in __init__
File "multiprocessing/synchronize.py", line 57, in __init__
PermissionError: [Errno 13] Permission denied
[25356] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by Agotech22** [comment]
> Probably related, got this from "epic alternative login method" [snap, 2.10.0]
> 
> ```
> An error has occurred! Try to Logout and Login on your Epic account.
> Traceback (most recent call last):
> File "legendary/cli.py", line 3148, in <module>
> File "legendary/cli.py", line 3032, in main
> File "legendary/cli.py", line 48, in setup_threaded_logging
> File "multiprocessing/context.py", line 103, in Queue
> File "multiprocessing/queues.py", line 43, in __init__
> File "multiprocessing/context.py", line 68, in LockFile "multiprocessing/synchronize.py", line 162, in __init__
> File "multiprocessing/synchronize.py", line 57, in __init__
> PermissionError: [Errno 13] Permission denied
> [25356] Failed to execute script 'cli' due to unhandled exception!
> ```

Yes, when I tried the alternative log in option for Epic Games, I got the same error as this:

**Comment by arielj** [comment]
the snap installer (used by ubuntu's store) is not stable enough, it has issues

we don't recommend to use it (we are trying to solve limitations of the snap packaging format)

**Comment by Agotech22** [comment]
Ok, when will a stable update be provided?

**Comment by arielj** [comment]
there's no timeline, whenever it gets fixed

2.10 fixed some issues that were present in 2.9 for example, but there are limitations using Snap that are not easy to solve so we don't know when that will happen

**Comment by Agotech22** [comment]
Ok, thanks, will close this problem.

**Comment by carnival4736** [comment]
@arielj I don't know where to send a pull request for this but I have solved the issue regarding my problem, although the EACCES problem still occurs, I am able to login to epic games in heroic now.

My problem's root cause was not having access to /dev/shm which was solved by doing this:
`# snap download heroic`
`# unsquashfs heroic_265.snap`
`# nano squashfs-root/meta/snap.yaml`
```
...
plugs:
  shmem:
    interface: shared-memory
    private: true
apps:
  heroic:
    command: command.sh
    plugs:
      - shmem
...
```
`# snap pack squashfs-root`
`# snap install heroic_2.10.0_amd64.snap --dangerous`

**Comment by arielj** [comment]
cc @flavioislima

in case this information helps with the snap work you were doing

**Comment by flavioislima** [comment]
> cc @flavioislima
> 
> in case this information helps with the snap work you were doing

This was fixed by one of my PRs before the last release. Should be fine now in the Snap.

**Comment by KillerbodyOrNot** [comment]
> > cc @flavioislima
> > in case this information helps with the snap work you were doing
> 
> This was fixed by one of my PRs before the last release. Should be fine now in the Snap.

I still have the issue. 
I also downloaded it from the ubuntu software center and it shows the version 2.12.0. 

Same difference, or maybe just not recognised by the previous reporter, is that I also get it, when I try to start a game from a already downloaded windows executable. It stil shows the game as launching, but nothing happens. And if I press "play now" it shows the error again. 

I would be open to download the launcher from another source, but could you then provide a link here? 

Thanks anyways.

**Comment by RandomDudeWithProblems** [comment]
> > > cc @flavioislima
> > > in case this information helps with the snap work you were doing
> > 
> > 
> > This was fixed by one of my PRs before the last release. Should be fine now in the Snap.
> 
> I still have the issue. I also downloaded it from the ubuntu software center and it shows the version 2.12.0.
> 
> Same problem, but the difference, or maybe just not recognised by the previous reporter, is that I also get it, when I try to start a game from a already downloaded windows executable. It stil shows the game as launching, but nothing happens. And if I press "play now" it shows the error again.
> 
> I would be open to download the launcher from another source, but could you then provide a link here?
> 
> Thanks anyways.

Solved it, just installed the newest version 2.14.1 from the website.

I let this comment here for others with this problem
