### ISSUE TITLE
It is not possible to log in again at Amazon

### ISSUE THREAD

**Issue by GamerPlayer888** [Heroic-Games-Launcher/HeroicGamesLauncher#3362]
### Describe the bug

I logged out of my accounts because not all my games are listed even after forcing the library update. Now I can no longer play my Amazon games, I'm stuck at the "Preparing to login..." page.

### Add logs

```text
[29/12/2023, 23:01:54] NILE_CONFIG_PATH=/home/eight/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
1.0.0 Jonathan Joestar
[29/12/2023, 23:03:06] NILE_CONFIG_PATH=/home/eight/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile auth --login --non-interactive
ERROR [CLI]:	 You are already logged in
[29/12/2023, 23:12:07] NILE_CONFIG_PATH=/home/eight/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
1.0.0 Jonathan Joestar
[29/12/2023, 23:13:42] NILE_CONFIG_PATH=/home/eight/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile auth --login --non-interactive
ERROR [CLI]:	 You are already logged in
[29/12/2023, 23:15:39] NILE_CONFIG_PATH=/home/eight/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile auth --login --non-interactive
ERROR [CLI]:	 You are already logged in
[29/12/2023, 23:19:09] NILE_CONFIG_PATH=/home/eight/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile auth --login --non-interactive
ERROR [CLI]:	 You are already logged in
[29/12/2023, 23:21:57] NILE_CONFIG_PATH=/home/eight/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile auth --login --non-interactive
ERROR [CLI]:	 You are already logged in
[29/12/2023, 23:23:33] NILE_CONFIG_PATH=/home/eight/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile --version
1.0.0 Jonathan Joestar
[29/12/2023, 23:32:12] NILE_CONFIG_PATH=/home/eight/.config/heroic/nile_config /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/nile auth --login --non-interactive
ERROR [CLI]:	 You are already logged in
```

### Steps to reproduce

1. Go to 'Manage Accounts'
2. Click on 'Amazon Log Out'
2. Click on 'Amazon Login'

### Expected behavior

After logging out, I can log back into my account.

### Screenshots

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/66787796/21042338-ac70-4ffc-8161-6b2a4358d62e

### Heroic Version

Latest Stable

### System Information

CPU: 8x Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
Memory: 8.17 GB (used: 4.53 GB)
GPUs:
  GPU 0:
    Name: NVIDIA Corporation GM108M [GeForce MX130]
    IDs: D=174d V=10de SD=128e SV=1025
    Driver: nvidia
  GPU 1:
    Name: Intel Corporation WhiskeyLake-U GT2 [UHD Graphics 620]
    IDs: D=3ea0 V=8086 SD=128d SV=1025
    Driver: i915
OS: Arch Linux 6.5.6-zen2-1-zen (linux)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.11.0 Kumachi
  Legendary: 0.20.33 Undue Alarm
  gogdl: 0.7.3
  Nile: 1.0.0 Jonathan Joestar

**Comment by SkalCore** [comment]
simply delete the files "user.json, library.json and installed.json in the following directory "Homedir/.config/heroic/nile_config/nile/"and restart Heroic, then it worked again for me

**Comment by ahkdigital** [comment]
@SkalCore 's solution worked for me as well. For anyone who might find this and it using the Flatpak - the files to delete were located in the folder here:

~/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config/nile

 _OS: Ubuntu 23.10_

**Comment by iran-cartazfacil** [comment]
Thanks! This solution by @SkalCore resolved the issue.

**Comment by Arndtagonist** [comment]
Sorry to open this again, but I have the very same issue but on windows. Reinstalling doesn't work because heroic saves the login information and i can't "clean" deinstall it.
I can't locate the named files (if they even exist on the windows version). Any ideas?

**Comment by arielj** [comment]
> Sorry to open this again, but I have the very same issue but on windows. Reinstalling doesn't work because heroic saves the login information and i can't "clean" deinstall it. I can't locate the named files (if they even exist on the windows version). Any ideas?

on windows, heroic's config folder is in C:\Users\<your user>\AppData\Local\Programs\heroic

**Comment by Arndtagonist** [comment]
> > Sorry to open this again, but I have the very same issue but on windows. Reinstalling doesn't work because heroic saves the login information and i can't "clean" deinstall it. I can't locate the named files (if they even exist on the windows version). Any ideas?
> 
> on windows, heroic's config folder is in C:\Users<your user>\AppData\Local\Programs\heroic

Thank you for your help. I already located the folder (difficult because it is hidden) but I can't find the both files in question. Also when I deinstall heroic the folder is gone, but my logins etc. are saved nonetheless (apparently somewhere else).

**Comment by Harmonia2Side** [comment]
> simply delete the files "user.json, library.json and installed.json" in the following directory "Homedir/.config/heroic/nile_config/nile/" and restart Heroic, then it worked again for me

Thank you very much! Solved the problem for me as well

**Comment by D4vidGarcia** [comment]
> > > Sorry to open this again, but I have the very same issue but on windows. Reinstalling doesn't work because heroic saves the login information and i can't "clean" deinstall it. I can't locate the named files (if they even exist on the windows version). Any ideas?
> > 
> > 
> > on windows, heroic's config folder is in C:\Users\AppData\Local\Programs\heroic
> 
> Thank you for your help. I already located the folder (difficult because it is hidden) but I can't find the both files in question. Also when I deinstall heroic the folder is gone, but my logins etc. are saved nonetheless (apparently somewhere else).

I found them on C:\Users\<your user>\AppData\Roaming\heroic\nile_config\nile

**Comment by dbophxlip2017** [comment]
I just had this issue.

I fixed it just by renaming the "nile_config" and "nile_store" folders and then relaunching Heroic.

**Comment by TOGLK** [comment]
I had this bug happen to me the other day,

I will provide some context so that hopefully the developers can have more details to work from to get this bug fixed.

Firstly I can 100% confirm this is a bug with Heroic's "Account Management" system and that it does NOT affect the Internal browser that Heroic Launcher uses because I was able to log back into my Amazon Prime Gaming (Amazon Prime) account by frequently ignoring the warning to use the built-in account management system and instead I just treated Heroics Internal sandboxed browser window like a regular internet browser window.

Now, to fix the bug all I had to do was follow the instructions left by both @SkalCore & @ahkdigital whom without the help from those two contributors I would have never have been able to resolve my issue by myself without further interaction or intervention by one of the Heroic Launcher Developers.

Once I had deleted those files listed by Skal & ahk it was plain sailing.

Now I was using a Steam Deck for all of this, so all I did was entered the "Desktop Mode" using the Power Controls in the Steam Decks default "Gaming Mode" left-side menu, once I was in "Desktop Mode" it was easy enough to navigate to where the Heroic Games Launcher Flatpak files were located and then simply manually delete them one at a time.

My Steam Deck is running the latest software and OS version supported on it at the time of writing which is;
• SteamOS Version - 3.6.22
• SteamOS Build Version - 20250224.1
• Kernel Version - 6.5.0-valve23-1-neptune-65-g385b5e207ae2
• BIOS Version - F7A0131

And here are the details for Heroic Games Launcher;
• Heroic Version - 2.16.0
• Install Type - Official Flatpak

Hopefully I have provided useful additional information, please try to fix this bug as it was rather annoying and less experienced users may panic or even just think that the app is unfixable given it took me a while to find this Git Repo Bug Report and I knew where to look as I frequent GitHub regularly.

**Comment by Dorsk82** [comment]
I am having the same issue on Steam Deck. Deleting user.json, library.json and installed.json did not solve my problem. I hope this gets a fix soon. Any other suggestions?

**Comment by tydog98** [comment]
Also having this issue with the Flatpak

**Comment by starblursd** [comment]
> simply delete the files "user.json, library.json and installed.json" in the following directory "Homedir/.config/heroic/nile_config/nile/" and restart Heroic, then it worked again for me

that fixed it for me as well thank you kind citizen

**Comment by h0m3** [comment]
> simply delete the files "user.json, library.json and installed.json" in the following directory "Homedir/.config/heroic/nile_config/nile/" and restart Heroic, then it worked again for me

Can also confirm,

Had the same problem and the same solution fixed.

For those using flatpak the path is `${HOME}/.var/app/com.heroicgameslauncher.hgl/config/heroic/nile_config/nile/`

**Comment by BloodySeraph** [comment]
> simply delete the files "user.json, library.json and installed.json" in the following directory "Homedir/.config/heroic/nile_config/nile/" and restart Heroic, then it worked again for me

This also fixed it on my end, on Windows. The path was obviously a bit different, namely `%appdata%/heroic/nile_config/nile`, but same idea of deleting those 3 files and restarting Heroic

**Comment by donut** [comment]
Having this issue on macOS. The path for `nile` directory is <code>/Users/**\<username\>**/Library/Application Support/heroic/nile_config/nile</code>. Also, instead of `user.json` it's `current_user.json`.

Had to log in twice. Not sure why. Second time stuck.
