### ISSUE TITLE
Epic Games won't launch

### ISSUE THREAD

**Issue by Garrythetuna** [Heroic-Games-Launcher/HeroicGamesLauncher#3397]
### Describe the bug

Games installed from epic games won't launch after "Play Now" Button is pressed, it just changed to "Playing" status for a brief without actually launching the game and then after that went back to "Play Now" button

Error message: 

An error has occurred! Try to Logout and Login on your Epic account.
[cli] INFO: Using prefix "/mnt/Amogdrive/Games/Heroic/Prefixes/PC Building Simulator"[cli] INFO: No Legendary-managed installation found.
Traceback (most recent call last):
File "legendary/cli.py", line 3148, in <module>
File "legendary/cli.py", line 3097, in main
File "legendary/cli.py", line 2229, in manage_eos_overlay
File "legendary/lfs/eos.py", line 52, in query_registry_entries
ValueError: No user.reg file, invalid path
[10612] Failed to execute script 'cli' due to unhandled exception!

### Add logs

```text
(16:28:13) WARNING: [DXVKInstaller]:    DXVK cannot be installed on a Proton or a invalid prefix!

(16:28:13) WARNING: [DXVKInstaller]:    DXVK cannot be installed on a Proton or a invalid prefix!

(16:28:13) INFO:    [Legendary]:        Launching PC Building Simulator: HEROIC_APP_NAME=ab277c0995e945d2b2c50c46883627f1 HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= DOTNET_BUNDLE_EXTRACT_BASE_DIR= DOTNET_ROOT= WINEPREFIX="/mnt/Amogdrive/Games/Heroic/Prefixes/PC Building Simulator" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 ORIG_LD_LIBRARY_PATH= LD_LIBRARY_PATH=/home/garry/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/lib64:/home/garry/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/lib GST_PLUGIN_SYSTEM_PATH_1_0=/home/garry/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/lib64/gstreamer-1.0:/home/garry/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/lib/gstreamer-1.0 WINEDLLPATH=/home/garry/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/lib64/wine:/home/garry/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/lib/wine LEGENDARY_CONFIG_PATH=/home/garry/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch ab277c0995e945d2b2c50c46883627f1 --wine /home/garry/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/bin/wine --language en

(16:28:14) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: LEGENDARY_CONFIG_PATH=/home/garry/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix "/mnt/Amogdrive/Games/Heroic/Prefixes/PC Building Simulator"

(16:28:14) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for PC Building Simulator

(16:28:14) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for PC Building Simulator

(16:28:14) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for PC Building Simulator

(16:28:14) INFO:    [ExtraGameInfo]:    Getting GamesDB data for PC Building Simulator

(16:28:14) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for PC Building Simulator

(16:28:14) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for PC Building Simulator

(16:28:14) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for PC Building Simulator

(16:28:14) INFO:    [ExtraGameInfo]:    Getting GamesDB data for PC Building Simulator

(16:28:14) INFO:    [Legendary]:        Getting more details with 'legendary info'

(16:28:14) INFO:    [Legendary]:        Getting more details with 'legendary info'

(16:28:15) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/garry/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary info ab277c0995e945d2b2c50c46883627f1 --json --platform Windows

(16:28:15) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/garry/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary info ab277c0995e945d2b2c50c46883627f1 --json --platform Windows

(16:28:15) DEBUG:   [Backend]:          ProtonDB data for 621060 {"bestReportedTier":"platinum","confidence":"strong","score":0.71,"tier":"gold","total":179,"trendingTier":"platinum"}

(16:28:15) DEBUG:   [Backend]:          SteamDeck data for 621060 {"success":1,"results":{"appid":621060,"resolved_category":3,"resolved_items":[{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_DefaultControllerConfigFullyFunctional"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_ControllerGlyphsMatchDeckDevice"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_InterfaceTextIsLegible"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_DefaultConfigurationIsPerformant"},{"display_type":1,"loc_token":"#SteamDeckVerified_TestResult_ExternalControllersNotSupportedPrimaryPlayer"}],"steam_deck_blog_url":"","search_id":null}}

(16:28:15) INFO:    [Backend]:          Stopping Display Power Saver Blocker

(16:28:15) INFO:    [Frontend]:         Refreshing legendary Library

(16:28:15) INFO:    [Legendary]:        Refreshing library...

(16:28:15) INFO:    [Legendary]:        Refreshing Epic Games...

(16:28:15) INFO:    [Legendary]:        Game list updated, got 39 games & DLCs

(16:28:15) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/garry/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party

(16:28:15) INFO:    [Legendary]:        Getting more details with 'legendary info'

(16:28:15) INFO:    [Legendary]:        Getting more details with 'legendary info'

(16:28:15) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/garry/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary info ab277c0995e945d2b2c50c46883627f1 --json --platform Windows

(16:28:15) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/garry/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary info ab277c0995e945d2b2c50c46883627f1 --json --platform Windows

(16:28:15) DEBUG:   [Backend]:          ProtonDB data for 621060 {"bestReportedTier":"platinum","confidence":"strong","score":0.71,"tier":"gold","total":179,"trendingTier":"platinum"}

(16:28:16) DEBUG:   [Backend]:          SteamDeck data for 621060 {"success":1,"results":{"appid":621060,"resolved_category":3,"resolved_items":[{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_DefaultControllerConfigFullyFunctional"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_ControllerGlyphsMatchDeckDevice"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_InterfaceTextIsLegible"},{"display_type":4,"loc_token":"#SteamDeckVerified_TestResult_DefaultConfigurationIsPerformant"},{"display_type":1,"loc_token":"#SteamDeckVerified_TestResult_ExternalControllersNotSupportedPrimaryPlayer"}],"steam_deck_blog_url":"","search_id":null}}

(16:28:16) INFO:    [Legendary]:        Getting Info from Epic API

(16:28:16) INFO:    [Legendary]:        Getting Info from Epic API

(16:33:14) INFO:    [Backend]:          Launching PC Building Simulator (ab277c0995e945d2b2c50c46883627f1)

(16:33:14) INFO:    [Backend]:          Checking if wine version exists: Wine - wine-ge-8-25-x86_64

(16:33:14) INFO:    [Backend]:          Stopping Power Saver Blocker

(16:33:14) DEBUG:   [Legendary]:        Using cached install info

(16:33:14) DEBUG:   [Legendary]:        Using cached install info

(16:33:14) DEBUG:   [Legendary]:        Using cached install info

(16:33:14) DEBUG:   [Legendary]:        Using cached install info

(16:33:14) INFO:    [Backend]:          Checking if wine version exists: Wine - wine-ge-8-25-x86_64

(16:33:14) INFO:    [Backend]:          Checking if wine version exists: Wine - wine-ge-8-25-x86_64

(16:33:14) INFO:    [Backend]:          Checking if wine version exists: Wine - wine-ge-8-25-x86_64

(16:33:14) DEBUG:   [Backend]:          Running Wine command: wineboot --init

(16:33:14) WARNING: [DXVKInstaller]:    DXVK cannot be installed on a Proton or a invalid prefix!

(16:33:14) WARNING: [DXVKInstaller]:    DXVK cannot be installed on a Proton or a invalid prefix!

(16:33:14) INFO:    [Legendary]:        Launching PC Building Simulator: HEROIC_APP_NAME=ab277c0995e945d2b2c50c46883627f1 HEROIC_APP_RUNNER=legendary HEROIC_APP_SOURCE=epic LD_PRELOAD= DOTNET_BUNDLE_EXTRACT_BASE_DIR= DOTNET_ROOT= WINEPREFIX="/mnt/Amogdrive/Games/Heroic/Prefixes/PC Building Simulator" WINEDLLOVERRIDES=winemenubuilder.exe=d WINE_FULLSCREEN_FSR=0 WINEESYNC=1 WINEFSYNC=1 ORIG_LD_LIBRARY_PATH= LD_LIBRARY_PATH=/home/garry/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/lib64:/home/garry/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/lib GST_PLUGIN_SYSTEM_PATH_1_0=/home/garry/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/lib64/gstreamer-1.0:/home/garry/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/lib/gstreamer-1.0 WINEDLLPATH=/home/garry/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/lib64/wine:/home/garry/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/lib/wine LEGENDARY_CONFIG_PATH=/home/garry/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch ab277c0995e945d2b2c50c46883627f1 --wine /home/garry/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/bin/wine --language en

(16:33:16) INFO:    [Backend]:          Stopping Display Power Saver Blocker

(16:33:16) INFO:    [Frontend]:         Refreshing legendary Library

(16:33:16) INFO:    [Legendary]:        Refreshing library...

(16:33:16) INFO:    [Legendary]:        Refreshing Epic Games...

(16:33:16) INFO:    [Legendary]:        Game list updated, got 39 games & DLCs

(16:33:16) DEBUG:   [Legendary]:        Using cached install info

(16:33:16) DEBUG:   [Legendary]:        Using cached install info

(16:33:17) INFO:    [Legendary]:        Running command: LEGENDARY_CONFIG_PATH=/home/garry/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary list --third-party

(16:36:14) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: LEGENDARY_CONFIG_PATH=/home/garry/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix "/mnt/Amogdrive/Games/Heroic/Prefixes/PC Building Simulator"

(16:36:14) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for PC Building Simulator

(16:36:14) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for PC Building Simulator

(16:36:14) DEBUG:   [Legendary]:        Using cached install info

(16:36:14) DEBUG:   [Legendary]:        Using cached install info

(16:39:11) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: LEGENDARY_CONFIG_PATH=/home/garry/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary eos-overlay info --prefix "/mnt/Amogdrive/Games/Heroic/Prefixes/PC Building Simulator"

(16:39:11) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for PC Building Simulator

(16:39:11) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for PC Building Simulator

(16:39:11) DEBUG:   [Legendary]:        Using cached install info

(16:39:11) DEBUG:   [Legendary]:        Using cached install info
```

### Steps to reproduce

1. Go to  Library
2. Click on any installed game
3. See error

### Expected behavior

Game launches

### Screenshots

![Screenshot from 2024-01-06 16-39-23](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/88380953/f9daa891-5221-4277-80e9-9b3662dcbfa3)

### Heroic Version

Latest Stable

### System Information

Ubuntu 22.04.3 LTS

**Comment by CommandMC** [comment]
The error message you're seeing is unrelated to the game launching (and, as an aside, should be resolved with 2.12.0)

**Comment by Garrythetuna** [comment]
i have installed the 2.12.0 and the error message isn't showing up anymore but i still can't get the game running. I've tried other games,and different drives but it still wouldn't launch

**Comment by arielj** [comment]
can you share a game log when you try to run a game? the one you shared is the general log

**Comment by Garrythetuna** [comment]
01d8:err:seh:call_stack_handlers invalid frame 00000000007ABD70 (00000000004B2000-00000000006B0000)
01d8:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.
01b4:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
01b4:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
01b4:fixme:dbghelp:elf_search_auxv can't find symbol in module
============= End of game logs =============

**Comment by Garrythetuna** [comment]
[message.txt](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/files/13998020/message.txt)

**Comment by arielj** [comment]
Looks like it's not a Heroic issue, seems like some problem with wine on your system.

You should move this to our Discord and create a thread in the `#-support` section, sharing game logs and reading the `read me first thread` in that section.

You probably want to re-install anything wine related and try again.

I'm closing this here since this Issues area in GitHub is for Heroic issues but Heroic is starting wine just fine, then it's wine that's failing.

**Comment by Garrythetuna** [comment]
okay, thanks for the suggestions
