### ISSUE TITLE
Can't login [Epic]

### ISSUE THREAD

**Issue by powerdollkirby** [Heroic-Games-Launcher/HeroicGamesLauncher#4525]
### Describe the bug

i tried both methods and they're not working
same result with both flatpak and aur 

![Image](https://github.com/user-attachments/assets/ead39cbc-8514-4483-9cd5-2e0b494ae987)
its stuck here
after a while it goes back to the manage accounts screen

### Add logs

```text
[15/05/2025, 15:41:34] LEGENDARY_CONFIG_PATH=/home/cassie/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary --version

legendary version "0.20.36", codename "Urban Flight (Heroic)"

[15/05/2025, 15:41:38] LEGENDARY_CONFIG_PATH=/home/cassie/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary auth --code <redacted>

[cli] INFO: Testing existing login data if present...

[EPCAPI] ERROR: Login to EGS API failed with errorCode: errors.com.epicgames.account.oauth.authorization_code_not_found

[Core] ERROR: Logging in failed with InvalidCredentialsError('errors.com.epicgames.account.oauth.authorization_code_not_found'), please try again.

[cli] ERROR: Login attempt failed, please see log for details.

[15/05/2025, 15:43:14] LEGENDARY_CONFIG_PATH=/home/cassie/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary auth --code <redacted>

[cli] INFO: Testing existing login data if present...

[EPCAPI] ERROR: Login to EGS API failed with errorCode: errors.com.epicgames.account.oauth.authorization_code_not_found

[Core] ERROR: Logging in failed with InvalidCredentialsError('errors.com.epicgames.account.oauth.authorization_code_not_found'), please try again.

[cli] ERROR: Login attempt failed, please see log for details.

[15/05/2025, 15:46:22] LEGENDARY_CONFIG_PATH=/home/cassie/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary auth --code <redacted>

[cli] INFO: Testing existing login data if present...
```

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

being  able to login

### Heroic Version

Latest Stable

### System Information

- CachyOS

**Comment by arielj** [comment]
I imagine you are having the issue that was fixed by https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/4478

so you have 2 options until the next release of heroic:
- downgrade to 2.16.0 to login
- use the build from the main branch here in github

I'll close this, if you test those options and it's not fixed we can reopen this

**Comment by powerdollkirby** [comment]
> I imagine you are having the issue that was fixed by [#4478](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/4478)
> 
> so you have 2 options until the next release of heroic:
> 
>     * downgrade to 2.16.0 to login
> 
>     * use the build from the main branch here in github
> 
> 
> I'll close this, if you test those options and it's not fixed we can reopen this

still the same
![Image](https://github.com/user-attachments/assets/5f0e5cdb-4dea-40a8-8383-9f6675578a92)

**Comment by arielj** [comment]
have you tried with the alternative login?

click `Log In` in the sidebar, then select the alternative login, it will ask you to log in with your browser and then copy an code into heroic

**Comment by powerdollkirby** [comment]
> have you tried with the alternative login?
> 
> click `Log In` in the sidebar, then select the alternative login, it will ask you to log in with your browser and then copy an code into heroic

like i said, i already tried both

**Comment by powerdollkirby** [comment]
what should i do?:(

**Comment by arielj** [comment]
some users that had issues logging in have reported that disabling IPV6 can help

some options to do that:
- disable IPV6 system-wide or in your router (this depends on your OS or router)
- temporarily connect to a cellphone connection (like a data plan of the phone)
- use a VPN

once you are logged in you can go back to the normal connection

**Comment by chmmou** [comment]
OS: CachyOS
Kernel: Linux 6.14.6-2-cachyos 
Heroic Version: 2.16.1

I have the same issue on CachyOS with Heroic Version 2.16.1.

When I try to log in, I receive the following information after successfully entering my login credentials. Of course, I have reloaded the page as suggested.

![Image1](https://github.com/user-attachments/assets/a1f2dd86-a137-4dc4-bcd9-93f31af4dbf8)

Then I wanted to know what the actual problem was and clicked on the “Open in browser” button in the top right corner and was able to log in successfully. I was then shown the following information, but I guess this is related to the fact that it is a GET request and not a POST request?

![Image2](https://github.com/user-attachments/assets/0da83cc1-dc9b-41eb-b6fa-cc759fc8985e)

I hope the information is helpful for you.

**Comment by styx9711** [comment]
having the same issue as [chmmou](https://github.com/chmmou) above .  i tried alternative signin and it doesn't work after being also unable to sign in the usual way .    

OS: Nobara 42 kde 
Kernel: 6.14.6-200.nobara.fc42.x86_64 (64-bit)
Heroic Version: 2.16.1

**Comment by powerdollkirby** [comment]
@arielj 

>     * disable IPV6 system-wide or in your router (this depends on your OS or router)
disabled ipv6, still doesn't work
>     * temporarily connect to a cellphone connection (like a data plan of the phone)

i have no possible way to try this since i dont have a wifi card or an android phone

>     * use a VPN
vpn doesn't seem to work either

**Comment by arielj** [comment]
is this fixed in Heroic 2.17.0?

**Comment by powerdollkirby** [comment]
still not working for me and this started happening to me on a fresh install
i installed the heroic-games-launcher-git too and it showed to login screen again, i logged in but still stuck in "https://www.epicgames.com/id/login?responseType=code" logging screen
alternative method still not working, idk what to do, everything was working fine before i did a fresh install

![Image](https://github.com/user-attachments/assets/0dee3e59-8888-4a0e-8222-ddcff37e7bcd)

**Comment by cassiedoxa** [comment]
still can't login, pls help
```

(23:27:55) INFO:    [Frontend]:         Called Epic Login

(23:27:55) INFO:    [Legendary]:        Logging in: LEGENDARY_CONFIG_PATH=/home/cassie/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary auth --code <redacted>

(23:28:13) ERROR:   [Legendary]:        Failed to login with Legendary: [cli] INFO: Testing existing login data if present...

[EPCAPI] ERROR: Login to EGS API failed with errorCode: errors.com.epicgames.account.oauth.authorization_code_not_found

[Core] ERROR: Logging in failed with InvalidCredentialsError('errors.com.epicgames.account.oauth.authorization_code_not_found'), please try again.

[cli] ERROR: Login attempt failed, please see log for details.

(23:28:24) ERROR:   [Legendary]:        Failed to login with Legendary: [cli] INFO: Testing existing login data if present...

[EPCAPI] ERROR: Login to EGS API failed with errorCode: errors.com.epicgames.account.oauth.authorization_code_not_found

[Core] ERROR: Logging in failed with InvalidCredentialsError('errors.com.epicgames.account.oauth.authorization_code_not_found'), please try again.

[cli] ERROR: Login attempt failed, please see log for details.
```
