### ISSUE TITLE
Fortnite thumbnails and gliders are broken

### ISSUE THREAD

**Issue by UltraSyko** [Heroic-Games-Launcher/HeroicGamesLauncher#4789]
### Describe the bug

This has been happening for a good month, but I waited for Fortnite and Heroic to update before making an issue. 
It's something related to the game not reading those files (or possibly a package). Glider cosmetics will either lack the model, animations, sounds or a combo of the three. Some will show render icons, some wont. Only a few gliders work, mostly the new ones in the current season. I have tried this on the latest update of both Fortnite and Heroic after a fresh reinstall and this is also happening to 3 of my friends. 

### Add logs

```text
(14:56:00) [INFO]:    [Backend]:         System Information: CPU: 24x AMD Ryzen 9 5900X 12-Core Processor            

Memory: 34.26 GB (used: 12.26 GB)

GPUs:

  GPU 0:

    Name: NVIDIA Corporation GA102 [GeForce RTX 3080 Lite Hash Rate]

    IDs: D=2216 V=10de SD=4885 SV=3842

    Driver: 576.52

OS: Microsoft Windows 11 Pro 10.0.26100 (win32)

The current system is not a Steam Deck

We are not running inside a Flatpak container

Software Versions:

  Heroic: 2.18.0 "Waterfall Beard" Jorul

  Legendary: 0.20.37 Exit 17 (Heroic)

  gogdl: 1.1.2

  comet: comet 0.2.0

  Nile: 1.1.2 Will A. Zeppeli

(14:56:00) [INFO]:    [Backend]:         Registered protocol with OS.

(14:56:00) [INFO]:    [Connection]:      Connectivity: check-online

(14:56:00) [ERROR]:   [Backend]:         failed to update Error: ENOENT: no such file or directory, open 'C:\Users\ssean\AppData\Local\Temp\30GxfOqURUjJaUnKxBEa7L4UdKj\resources\app-update.yml'

(14:56:00) [INFO]:    [Connection]:      Pinging external endpoints

(14:56:01) [ERROR]:   [Gog]:             Unable to syncQueued playtime, userData not present

(14:56:00) [INFO]:    [Gog]:             Checking for existing gog manifests

(14:56:01) [INFO]:    [Gog]:             Running command: GOGDL_CONFIG_PATH=C:\Users\ssean\AppData\Roaming\heroic\gogdlConfig powershell -NoProfile Start-Process "`"C:\Users\ssean\AppData\Local\Temp\30GxfOqURUjJaUnKxBEa7L4UdKj\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\ssean\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"auth`""

(14:56:01) [DEBUG]:   [Gog]:             Logging to file(s) "C:\Users\ssean\AppData\Local\Heroic\logs\runners\gog.log"

(14:56:01) [INFO]:    [Connection]:      Connectivity: online

(14:56:01) [WARNING]: refresh not implemented on Sideload Library Manager

(14:56:01) [INFO]:    [Frontend]:        Refreshing undefined Library

(14:56:01) [INFO]:    [Legendary]:       Refreshing Epic Games...

(14:56:01) [INFO]:    [Backend]:         Frontend Ready

(14:56:01) [INFO]:    [Legendary]:       Running command: LEGENDARY_CONFIG_PATH=C:\Users\ssean\AppData\Roaming\heroic\legendaryConfig\legendary powershell -NoProfile Start-Process "`"C:\Users\ssean\AppData\Local\Temp\30GxfOqURUjJaUnKxBEa7L4UdKj\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"list`"","`"--third-party`""

(14:56:01) [INFO]:    [Legendary]:       Refreshing library...

(14:56:01) [DEBUG]:   [Legendary]:       Logging to file(s) "C:\Users\ssean\AppData\Local\Heroic\logs\runners\legendary.log"

(14:56:01) [INFO]:    [Backend]:         VCRuntime is installed

(14:56:01) [INFO]:    [Backend]:         Checking for new Heroic Updates

(14:56:01) [INFO]:    [Legendary]:       Running command: LEGENDARY_CONFIG_PATH=C:\Users\ssean\AppData\Roaming\heroic\legendaryConfig\legendary powershell -NoProfile Start-Process "`"C:\Users\ssean\AppData\Local\Temp\30GxfOqURUjJaUnKxBEa7L4UdKj\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"cleanup`""

(14:56:01) [DEBUG]:   [Legendary]:       Logging to file(s) "C:\Users\ssean\AppData\Local\Heroic\logs\runners\legendary.log"

(14:56:01) [INFO]:    [Frontend]:        Updated to a new version, cleaaning up the cache.

(14:56:02) [INFO]:    [Nile]:            Running command: NILE_CONFIG_PATH=C:\Users\ssean\AppData\Roaming\heroic\nile_config powershell -NoProfile Start-Process "`"C:\Users\ssean\AppData\Local\Temp\30GxfOqURUjJaUnKxBEa7L4UdKj\resources\app.asar.unpacked\build\bin\x64\win32\nile`"" -Wait -NoNewWindow -ArgumentList "`"--version`""

(14:56:01) [INFO]:    [Legendary]:       Running command: LEGENDARY_CONFIG_PATH=C:\Users\ssean\AppData\Roaming\heroic\legendaryConfig\legendary powershell -NoProfile Start-Process "`"C:\Users\ssean\AppData\Local\Temp\30GxfOqURUjJaUnKxBEa7L4UdKj\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"--version`""

(14:56:01) [INFO]:    [Gog]:             Running command: GOGDL_CONFIG_PATH=C:\Users\ssean\AppData\Roaming\heroic\gogdlConfig powershell -NoProfile Start-Process "`"C:\Users\ssean\AppData\Local\Temp\30GxfOqURUjJaUnKxBEa7L4UdKj\resources\app.asar.unpacked\build\bin\x64\win32\gogdl`"" -Wait -NoNewWindow -ArgumentList "`"--auth-config-path`"","`"C:\\Users\\ssean\\AppData\\Roaming\\heroic\\gog_store\\auth.json`"","`"--version`""

(14:56:02) [DEBUG]:   [Legendary]:       Logging to file(s) "C:\Users\ssean\AppData\Local\Heroic\logs\runners\legendary.log"

(14:56:02) [DEBUG]:   [Nile]:            Logging to file(s) "C:\Users\ssean\AppData\Local\Heroic\logs\runners\nile.log"

(14:56:01) [INFO]:    [Backend]:         Checking for current version changelog

(14:56:02) [DEBUG]:   [Gog]:             Logging to file(s) "C:\Users\ssean\AppData\Local\Heroic\logs\runners\gog.log"

(14:56:03) [WARNING]: listUpdateableGames not implemented on Sideload Library Manager

(14:56:03) [INFO]:    [Legendary]:       Checking for game updates: LEGENDARY_CONFIG_PATH=C:\Users\ssean\AppData\Roaming\heroic\legendaryConfig\legendary powershell -NoProfile Start-Process "`"C:\Users\ssean\AppData\Local\Temp\30GxfOqURUjJaUnKxBEa7L4UdKj\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"list`"","`"--third-party`""

(14:56:03) [INFO]:    [Legendary]:       Game list updated, got 37 games & DLCs

(14:56:03) [DEBUG]:   [Legendary]:       Logging to file(s) "C:\Users\ssean\AppData\Local\Heroic\logs\runners\legendary.log"

(14:56:06) [INFO]:    [Legendary]:       Found 0 games to update

(14:56:06) [INFO]:    [Backend]:         Starting the Download Queue

(14:56:38) [INFO]:    [Backend]:         Launching Fortnite (Fortnite)

(14:56:38) [INFO]:    [Backend]:         Preventing display from sleep

(14:56:38) [INFO]:    [Backend]:         Preventing machine to sleep

(14:56:38) [INFO]:    [Legendary]:       Launching Fortnite: HEROIC_APP_NAME=Fortnite HEROIC_APP_RUNNER=legendary GAMEID=umu-0 HEROIC_APP_SOURCE=epic STORE=egs LD_PRELOAD= LEGENDARY_CONFIG_PATH=C:\Users\ssean\AppData\Roaming\heroic\legendaryConfig\legendary powershell -NoProfile Start-Process "`"C:\Users\ssean\AppData\Local\Temp\30GxfOqURUjJaUnKxBEa7L4UdKj\resources\app.asar.unpacked\build\bin\x64\win32\legendary`"" -Wait -NoNewWindow -ArgumentList "`"launch`"","`"Fortnite`"","`"--language`"","`"en`""

(14:56:38) [DEBUG]:   [Legendary]:       Logging to file(s) "C:\Users\ssean\AppData\Local\Heroic\logs\games\Fortnite_legendary\launch.log", "C:\Users\ssean\AppData\Local\Heroic\logs\runners\legendary.log"

(14:56:38) [INFO]:    [Backend]:         Preventing display to sleep
```

### Steps to reproduce

1. Go to 'Fortnite'
2. Check Gliders
3. See error

### Expected behavior

1. Go to 'Fortnite'
2. Check Gliders
3. Gliders display properly

### Screenshots

<img width="1270" height="1172" alt="Image" src="https://github.com/user-attachments/assets/1ab904e1-0a5a-4ab0-b249-14d9433a4005" />

<img width="1123" height="1016" alt="Image" src="https://github.com/user-attachments/assets/7227ae2d-15b9-4f86-8fca-88eca5bfb450" />

### Heroic Version

Latest Stable

### System Information

Windows 11

**Comment by Sylv25** [comment]
I'm having the exact same issue! Been playing Fortnite on Heroic Launcher and ever since last month been encountering this issue.

<img width="824" height="649" alt="Image" src="https://github.com/user-attachments/assets/30f62ea9-1673-49ff-864a-6062e09f072f" />

**Comment by RagdollClash** [comment]
I did a clean install the other day and ran into this exact isssue

<img width="2048" height="1152" alt="Image" src="https://github.com/user-attachments/assets/8cda8f2f-7020-4dde-ad87-e0beb31106dc" />

**Comment by dnfanjos** [comment]
Same! I tried borrowing a Fortnite Install from a friend (copying it to my c drive and using locate game) and I could see my gliders again, but after the latest update, heroic just repatched the pakchunks containing the gliders and they are gone once more. I tried verifying and repairing on both Heroic and using the Legendary addon for Playnite, but nothing worked. This issue only occurs on gliders and one specific car boost trail's thumbnail which is interesting...

![Image](https://github.com/user-attachments/assets/19907e2e-71df-4eeb-a264-aff166f93fa5)

**Comment by UltraSyko** [comment]
It's getting reeeeally bad. More gliders are broken in the latest update and if you didn't have any nvidia shaders cached prior. The game can't grab the game thumbnails <img width="3058" height="896" alt="Image" src="https://github.com/user-attachments/assets/46e6a15e-3816-4d8b-80a5-9e075e32833a" />

**Comment by arielj** [comment]
legendary has issues updating fortnite, you are probably better updating/reparing fornite with the official epic games launcher, then you can use heroic to launch it

**Comment by UltraSyko** [comment]
Great advice! Everything is good now
For anyone else that wants to fix it
Uninstall Fortnite
Download Epic Games Launcher
Install Fortnite
Import game via Heroic

**Comment by dnfanjos** [comment]
This sucks as a solution because if you let Heroic update your Fortnite install, it’s just gonna screw it up again. I don’t know how the epic launcher sync feature works, like if it allows me to handle updates with Epic. Or if I can just force the game to never auto update. But if Heroic is unable to handle Fortnite files, It could cause a lot of users to drop the launcher and just go back to the original. I know we still have GOG and Amazon support. But not that many people use those and would ditch support in favor of going back to Epic. But I understand if this issue isn’t quickly resolved as it must be a real pain for the heroes behind Heroic and its many dependencies.

**Comment by UltraSyko** [comment]
Trust me, I don't like it either. But it's the only way for now. Hopefully it gets fixed in the future

**Comment by arielj** [comment]
> But I understand if this issue isn’t quickly resolved as it must be a real pain for the heroes behind Heroic and its many dependencies.

the issue is not even in heroic, it's in legendary (it will happen with any application that uses legendary for the backend, like Rare or the legendary Playnite plugin)

**Comment by arielj** [comment]
> This sucks as a solution because if you let Heroic update your Fortnite install, it’s just gonna screw it up again. I don’t know how the epic launcher sync feature works, like if it allows me to handle updates with Epic. Or if I can just force the game to never auto update.

with the sync feature you can install and update fortnite with epic and then it should show as updated in heroic, and you can configure heroic to never update the game in the settings.

**Comment by Romz24** [comment]
> with the sync feature you can install and update fortnite with epic and then it should show as updated in heroic, and you can configure heroic to never update the game in the settings.

I specifically use Heroic Games Launcher instead of the Epic Games Launcher for Fortnite and other games. Your solution feels very inconvenient and basically forces us to use Epic again. So what’s the point of Heroic if I still have to install the Epic launcher anyway?

**Comment by arielj** [comment]
> > with the sync feature you can install and update fortnite with epic and then it should show as updated in heroic, and you can configure heroic to never update the game in the settings.
> 
> I specifically use Heroic Games Launcher instead of the Epic Games Launcher for Fortnite and other games. Your solution feels very inconvenient and basically forces us to use Epic again. So what’s the point of Heroic if I still have to install the Epic launcher anyway?

heroic was not made exclusively for fortnite, so the point of heroic is to be able to handle all the other games in epic, gog, amazon, and also support linux and mac

also, this is all open source done by people on their free time, you are welcome to find the fix for the problem and submit a PR for the legendary repo to properly update fortnite

**Comment by ZippyZolton** [comment]
This has gotten worse to the point where a default cosmetic is broken and makes the game crash when you try to play at all :c

**Comment by dnfanjos** [comment]
> This has gotten worse to the point where a default cosmetic is broken and makes the game crash when you try to play at all :c

_If you are talking about the current situation, it's not a launcher thing. Fortnite is just too bugged at the start of this season.
Verify and Repair, or predownload cache._

Edit: Can confirm it's a launcher Issue, darn

**Comment by PKPenguin321** [comment]
I can verify what @ZippyZolton says, Fortnite is now unplayable as player model assets fail to load. See also for Legendary: https://github.com/derrod/legendary/issues/711

**Comment by filcohere** [comment]
I had cosmetic not showing up before but worked fine until Simpsons update, now it's crashing, I just need to go to inventory and it's crash, I verify files, but that's not doing it correctly takes less than 1min, fortnite file size showing as 1.44GB, fornite folder 54.4GB and in downloads files size 128.95GB. My internet is very slow I don't want to start over again you should fix verify thing please :)

Edit: downloaded epic lautcher fortnite connected somehow when I clicked on it an appered in library, I try to run it and same thing crash in menu, so I try to verify files and noticed same problem 1.50GB of file size, so I still verify it and was at same speed very quick, now I clicked on manage and file size increased to 58.47GB, I'm going to verify again since it's biger file size this time.

**Comment by arielj** [comment]
This should be solved now, since legendary's SDL data was updated.

Eventually, this other PR should make things more future-proof https://github.com/derrod/legendary/pull/724.

**Comment by SupDos** [comment]
Unfortunately this doesn't seem to be fixed. Tried a fresh fortnite download using legendary (both the normal one and the heroic release) and still get the issue with no cosmetics loading. Game also crashes as mentioned above due to the default cosmetic not loading either.

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/84becf82-41ec-4d71-b680-7ef0bbc8df9a" />

@arielj Would the SDL fix require downloading it through Heroic or does standalone legendary work too? Maybe I'm doing something wrong?
